import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tFor: (lang: Language, key: string) => string;
  inBrazil: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Hero Section
    'hero.badge': 'Lançamento',
    'hero.title': 'Couples Financials',
    'hero.subtitle': 'Controle suas finanças de forma inteligente',
    'hero.description': 'Idealizado para casais, mas recomendamos para todos. Planeje, economize e invista com ajuda da IA.',
    'hero.cta.free': 'Baixe Gratuitamente',
    'hero.cta.premium': 'Experimente a versão com IA por R$ 19,90',
    
    // Header
    'header.login': 'Entrar',
    'header.comingSoon': 'Funcionalidade em breve.',
    
    // Benefits Section
    'benefits.title': 'Por que escolher o',
    'benefits.subtitle': 'Recursos inovadores para controle financeiro completo',
    'benefits.shared.title': 'Gestão financeira compartilhada ou individual',
    'benefits.shared.description': 'Controle suas finanças sozinho ou compartilhe com seu parceiro',
    'benefits.multicurrency.title': 'Controle em múltiplas moedas',
    'benefits.multicurrency.description': 'Gerencie gastos em diferentes moedas com conversão automática',
    'benefits.ai.title': 'Planejamento inteligente com IA',
    'benefits.ai.description': 'Saiba quanto poupar e onde investir com recomendações personalizadas',
    'benefits.miles.title': 'Ferramenta de milhas inteligente',
    'benefits.miles.description': 'Veja promoções e use suas milhas com inteligência',
    'benefits.voice.title': 'Input por voz via WhatsApp',
    'benefits.voice.description': 'Fale com o robô e registre seus gastos sem digitar',
    'benefits.security.title': 'Segurança e privacidade garantidas',
    'benefits.security.description': 'Seus dados financeiros protegidos com criptografia avançada',
    
    // Dashboard
    'dashboard.title': 'Gestão Financeira para Casais',
    'dashboard.subtitle': 'Controle suas finanças de forma inteligente',
    'dashboard.balance': 'Saldo Total',
    'dashboard.income': 'Receitas',
    'dashboard.expenses': 'Despesas',
    'dashboard.addTransaction': 'Adicionar Transação',
    'dashboard.viewMode': 'Modo de Visualização',
    'dashboard.both': 'Ambos',
    'dashboard.user1': 'Usuário 1',
    'dashboard.user2': 'Usuário 2',
    'dashboard.sharedActiveBanner': 'Dashboard compartilhado ativo - mostrando dados de ambos os usuários',
    'dashboard.individualInviteBanner': 'Dashboard individual - convide seu parceiro(a) para compartilhar dados',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Gastos Mensais',
    'nav.monthlyIncome': 'Receitas Mensais',
    'nav.categories': 'Categorias',
    'nav.recurring': 'Gastos Recorrentes',
    'nav.cards': 'Cartões',
    'nav.accounts': 'Contas',
    'nav.profile': 'Perfil',
    'nav.investments': 'Investimentos',
    'nav.mileage': 'Milhagem',
    'nav.back': 'Voltar',
    'nav.admin': 'Admin',
    'nav.subscription': 'Planos',
    'nav.testEmail': 'Teste Email',
    'nav.logout': 'Sair',
    
    // Cards
    'cards.title': 'Gerenciar Cartões',
    'cards.manage': 'Gerenciar Cartões',
    'cards.add': 'Adicionar Cartão',
    'cards.name': 'Nome do Cartão',
    'cards.type': 'Tipo do Cartão',
    'cards.credit': 'Crédito',
    'cards.debit': 'Débito',
    'cards.lastFourDigits': 'Últimos 4 Dígitos',
    'cards.creditLimit': 'Limite de Crédito',
    'cards.currentBalance': 'Saldo Atual',
    'cards.currency': 'Moeda',
    'cards.dueDate': 'Data de Vencimento',
    'cards.selectType': 'Selecione o tipo',
    'cards.selectDay': 'Selecione o dia',
    'cards.adding': 'Adicionando...',
    'cards.addCard': 'Adicionar Cartão',
    
    // Accounts
    'accounts.title': 'Gerenciar Contas',
    'accounts.manage': 'Gerenciar Contas',
    'accounts.add': 'Adicionar Conta',
    'accounts.name': 'Nome da Conta',
    'accounts.type': 'Tipo da Conta',
    'accounts.types.checking': 'Conta Corrente',
    'accounts.types.savings': 'Poupança',
    'accounts.types.investment': 'Investimento',
    'accounts.types.other': 'Outra',
    'accounts.models.personal': 'Pessoal',
    'accounts.models.business': 'Empresarial',
    'accounts.yourAccounts': 'Suas Contas',
    'accounts.noAccounts': 'Nenhuma conta cadastrada',
    'accounts.balance': 'Saldo',
    'accounts.bank': 'Banco',
    'accounts.selectType': 'Selecione o tipo',
    'accounts.adding': 'Adicionando...',
    'accounts.addAccount': 'Adicionar Conta',
    
    // Common
    'common.required': 'obrigatório',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.loading': 'Carregando...',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.select': 'Selecionar',
    'back': 'Voltar',
    
    // TransactionForm
    'transactionForm.title': 'Nova Transação',
    'transactionForm.income': 'Receita',
    'transactionForm.expense': 'Despesa',
    'transactionForm.transactionDate': 'Data da Transação',
    'transactionForm.selectDate': 'Selecionar data',
    'transactionForm.amount': 'Valor',
    'transactionForm.description': 'Descrição',
    'transactionForm.receiptMethod': 'Método de Recebimento',
    'transactionForm.paymentMethod': 'Método de Pagamento',
    'transactionForm.selectPaymentMethod': 'Selecionar método',
    'transactionForm.cash': 'Dinheiro',
    'transactionForm.deposit': 'Depósito',
    'transactionForm.transfer': 'Transferência',
    'transactionForm.debitCard': 'Cartão de Débito',
    'transactionForm.creditCard': 'Cartão de Crédito',
    'transactionForm.category': 'Categoria',
    'transactionForm.selectCategory': 'Selecionar categoria',
    'transactionForm.subcategory': 'Subcategoria',
    'transactionForm.currency': 'Moeda',
    'transactionForm.addTransaction': 'Adicionar Transação',
    'transactionForm.paymentTransfer': 'Transferência de Pagamento',
    'transactionForm.receivedTransfer': 'Transferência Recebida',
    'transactionForm.accountTransfer': 'Transferência entre Contas',
    'transactionForm.accountInvestmentTransfer': 'Transferência Conta-Investimento',
    'transactionForm.selectAccount': 'Selecionar Conta',
    'transactionForm.selectAccountPlaceholder': 'Escolha uma conta',
    'transactionForm.selectSourceAccount': 'Conta de Origem',
    'transactionForm.selectDestinationAccount': 'Conta de Destino',
    'transactionForm.selectInvestment': 'Selecionar Investimento',
    
    // Auth
    'auth.appName': 'Couples Financials',
    'auth.tagline': 'Gestão financeira compartilhada para casais',
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Criar Conta',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'seu@email.com',
    'auth.password': 'Senha',
    'auth.tempPassword': 'Senha Temporária',
    'auth.tempPasswordPlaceholder': 'Digite a senha temporária',
    'auth.name': 'Nome',
    'auth.yourName': 'Seu nome',
    'auth.createAccount': 'Criar Conta',
    'auth.continueWithGoogle': 'Continuar com Google',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.resetEmailSend': 'Enviar Email de Recuperação',
    'auth.backToLogin': 'Voltar ao Login',
    'auth.inviteBanner': 'Você foi convidado! Use a senha temporária enviada por email.',
    'auth.loginSuccessTitle': 'Login realizado!',
    'auth.loginSuccessDesc': 'Bem-vindo de volta.',
    'auth.loginErrorTitle': 'Erro no login',
    'auth.loginErrorDesc': 'Verifique suas credenciais e tente novamente.',
    'auth.googleErrorTitle': 'Erro no Google',
    'auth.signupSuccessTitle': 'Conta criada com sucesso!',
    'auth.signupSuccessDesc': 'Verifique seu email para confirmar sua conta.',
    'auth.signupErrorTitle': 'Erro ao criar conta',
    'auth.signupErrorDesc': 'Ocorreu um erro. Tente novamente.',
    'auth.emailRequiredTitle': 'Email obrigatório',
    'auth.emailRequiredDesc': 'Por favor, insira seu email.',
    'auth.resetEmailTitle': 'Email enviado!',
    'auth.resetEmailDesc': 'Verifique sua caixa de entrada.',
    'auth.resetEmailErrorTitle': 'Erro ao enviar email',
    'auth.resetEmailErrorDesc': 'Tente novamente mais tarde.',
    
    // Categories
    'categories.title': 'Gerenciar Categorias',
    'categories.add': 'Adicionar Categoria',
    'categories.edit': 'Editar Categoria',
    'categories.heading': 'Categorias',
    'categories.name': 'Nome da Categoria',
    'categories.placeholder': 'Ex: Alimentação, Transporte...',
    'categories.color': 'Cor',
    'categories.type': 'Tipo',
    'categories.type.expense': 'Saída',
    'categories.type.income': 'Entrada',
    'categories.filter.all': 'Todas as Categorias',
    'categories.filter.income': 'Categorias de Entrada',
    'categories.filter.expense': 'Categorias de Saída',
    'categories.create': 'Criar',
    'categories.update': 'Atualizar',
    'categories.none': 'Nenhuma categoria cadastrada. Crie sua primeira categoria!',
    
    // Charts
    'charts.userAnalysisTitle': 'Análise Financeira por Usuário',
    'charts.userComparison': 'Comparativo entre Usuários',
    'charts.expenses': 'Gastos',
    'charts.income': 'Receitas',
    'charts.currentMonth': 'Mês Atual',
    'charts.last3Months': '3 Meses',
    'charts.last6Months': '6 Meses',
    'charts.pieChart': 'Pizza',
    'charts.barChart': 'Barras',
    'charts.total': 'Total',
    'charts.user1': 'Usuário 1',
    'charts.user2': 'Usuário 2',
    'charts.noData': 'Nenhum {type} encontrado no período',
    
    // Theme
    'theme.light': 'Claro',
    'theme.dark': 'Escuro',
    
    // Messages
    'messages.cardAdded': 'Cartão adicionado com sucesso!',
    'messages.cardError': 'Erro ao adicionar cartão',
    'messages.accountAdded': 'Conta adicionada com sucesso!',
    'messages.accountError': 'Erro ao carregar conta',
    'messages.accountDeleted': 'Conta removida com sucesso!',
    'messages.accountDeleteError': 'Erro ao remover conta',
    'messages.categoryAdded': 'Categoria adicionada com sucesso!',
    'messages.categoryError': 'Erro ao adicionar categoria',
    'messages.transactionAdded': 'Transação adicionada com sucesso!',
    'messages.transactionError': 'Erro ao adicionar transação',
    'messages.duplicateAccountName': 'Já existe uma conta com este nome. Altere e tente novamente.',
    
    // Investments
    'investments.title': 'Investimentos',
    'investments.dashboard': 'Dashboard de Investimentos',
    'investments.newInvestment': 'Novo Investimento',
    'investments.totalInvested': 'Total Investido',
    'investments.currentValue': 'Valor Atual',
    'investments.totalReturn': 'Retorno Total',
    'investments.returnPercentage': 'Retorno %',
    'investments.distribution': 'Distribuição por Tipo',
    'investments.name': 'Nome do Investimento',
    'investments.type': 'Tipo',
    'investments.amount': 'Valor Investido',
    'investments.currentValueField': 'Valor Atual',
    'investments.purchaseDate': 'Data de Compra',
    'investments.broker': 'Corretora',
    'investments.goal': 'Meta',
    'investments.currency': 'Moeda',
    'investments.notes': 'Observações',
    'investments.isShared': 'Investimento Compartilhado',
    'investments.selectType': 'Selecione o tipo',
    'investments.selectGoal': 'Selecione uma meta',
    'investments.creating': 'Criando...',
    'investments.createInvestment': 'Criar Investimento',
    'investments.goals': 'Objetivos',
    'investments.overview': 'Visão Geral',
    'investments.activeGoals': 'Objetivos Ativos',
    'investments.goalName': 'Nome da Meta',
    'investments.targetAmount': 'Valor Meta',
    'investments.currentAmount': 'Valor Atual',
    'investments.targetDate': 'Data Meta',
    'investments.description': 'Descrição',
    'investments.completed': 'Concluída',
    'investments.inProgress': 'Em Progresso',
    'investments.progress': 'Progresso',
    'investments.profitabilitySimulator': 'Simulador de Rentabilidade',
    'investments.portfolioChart': 'Gráfico do Portfólio',
    'investments.noInvestments': 'Nenhum investimento encontrado',
    'investments.noGoals': 'Nenhuma meta encontrada',
    'investments.noData': 'Nenhum dado disponível',
    'investments.actions': 'Ações',
    'investments.date': 'Data',
    'investments.shared': 'Compartilhado',
    'investments.listTitle': 'Lista de Investimentos',
    'investments.addInvestment': 'Adicionar Investimento',
    
    // User Profile & Invites
    'userProfile.title': 'Perfil do Usuário',
    'userProfile.profile': 'Perfil',
    'userProfile.users': 'Usuários',
    'userProfile.billing': 'Faturamento',
    'userProfile.security': 'Segurança',
    'userProfile.personalInfo': 'Informações Pessoais',
    'userProfile.email': 'E-mail',
    'userProfile.displayName': 'Nome de Exibição',
    'userProfile.preferredCurrency': 'Moeda Preferida',
    'userProfile.saving': 'Salvando...',
    'userProfile.saveProfile': 'Salvar Perfil',
    'userProfile.userConfig': 'Configuração de Usuários',
    'userProfile.mainUser': 'Usuário Principal',
    'userProfile.secondUser': 'Segundo Usuário',
    'userProfile.inviteEmail': 'E-mail para Convite',
    'userProfile.sending': 'Enviando...',
    'userProfile.sendInvite': 'Enviar Convite',
    'userProfile.saveSettings': 'Salvar Configurações',
    'userProfile.billingInfo': 'Informações de Faturamento',
    'userProfile.freePlan': 'Você está no plano gratuito',
    'userProfile.upgradeText': 'Faça upgrade para acessar recursos premium',
    'userProfile.upgradePlan': 'Fazer Upgrade',
    'userProfile.changePassword': 'Alterar Senha',
    'userProfile.newPassword': 'Nova Senha',
    'userProfile.confirmPassword': 'Confirmar Senha',
    'userProfile.updating': 'Atualizando...',
    'userProfile.updatePassword': 'Atualizar Senha',
    
    // Invite Card
    'inviteCard': 'Convidar Parceiro(a)',
    'inviteSubtext': 'Compartilhe suas finanças',
    
    // Mileage
    'mileage.title': 'Sistema de Milhagem',
    'mileage.subtitle': 'Gerencie suas milhas de cartão de crédito e metas de viagem',
    'mileage.backToDashboard': 'Voltar ao Dashboard',
    'mileage.totalMiles': 'Total de Milhas',
    'mileage.milesAccumulated': 'milhas acumuladas',
    'mileage.activeCards': 'Cartões Ativos',
    'mileage.rulesConfigured': 'regras configuradas',
    'mileage.activeGoals': 'Metas Ativas',
    'mileage.inProgress': 'em progresso',
    'mileage.rules': 'Regras de Milhagem',
    'mileage.goals': 'Metas',
    'mileage.history': 'Histórico',
    'mileage.newRule': 'Nova Regra',
    'mileage.newGoal': 'Nova Meta',
    'mileage.ruleTitle': 'Nova Regra de Milhagem',
    'mileage.ruleDescription': 'Configure como as milhas são calculadas para um cartão específico',
    'mileage.card': 'Cartão',
    'mileage.selectCard': 'Selecione um cartão',
    'mileage.bankName': 'Nome do Banco',
    'mileage.bankPlaceholder': 'Ex: Nubank, Itaú, Bradesco',
    'mileage.cardBrand': 'Bandeira',
    'mileage.brandPlaceholder': 'Ex: Visa, Mastercard, Elo',
    'mileage.currency': 'Moeda',
    'mileage.milesPerAmount': 'Milhas por Valor',
    'mileage.milesPlaceholder': 'Ex: 1 (1 milha)',
    'mileage.amountThreshold': 'A cada',
    'mileage.thresholdPlaceholder': 'Ex: 3 (R$ 3,00 gastos)',
    'mileage.createRule': 'Criar Regra',
    'mileage.active': 'Ativo',
    'mileage.inactive': 'Inativo',
    'mileage.activate': 'Ativar',
    'mileage.deactivate': 'Desativar',
    'mileage.milesEarned': 'milhas',
    'mileage.goalTitle': 'Nova Meta de Milhagem',
    'mileage.goalDescription': 'Defina uma meta para acumular milhas',
    'mileage.goalName': 'Nome da Meta',
    'mileage.goalNamePlaceholder': 'Ex: Viagem para Europa',
    'mileage.targetMiles': 'Milhas Necessárias',
    'mileage.targetMilesPlaceholder': 'Ex: 50000',
    'mileage.targetDate': 'Data Meta (Opcional)',
    'mileage.description': 'Descrição (Opcional)',
    'mileage.descriptionPlaceholder': 'Descreva sua meta...',
    'mileage.createGoal': 'Criar Meta',
    'mileage.completed': 'Concluída',
    'mileage.progressText': 'concluído',
    'mileage.target': 'Meta',
    'mileage.historyTitle': 'Histórico de Milhagem',
    'mileage.spent': 'Gasto',
    'mileage.ruleCreated': 'Regra de milhagem criada com sucesso',
    'mileage.ruleCreateError': 'Erro ao criar regra de milhagem',
    'mileage.goalCreated': 'Meta de milhagem criada com sucesso',
    'mileage.goalCreateError': 'Erro ao criar meta de milhagem',
    'mileage.ruleDeleted': 'Regra deletada com sucesso',
    'mileage.ruleDeleteError': 'Erro ao deletar regra',
    'mileage.goalDeleted': 'Meta deletada com sucesso',
    'mileage.goalDeleteError': 'Erro ao deletar meta',
    'mileage.ruleStatusError': 'Erro ao atualizar status da regra',
    
    // Admin
    'admin.title': 'Painel Administrativo',
    'admin.subtitle': 'Gerenciar usuários e assinaturas do sistema',
    'admin.accessDenied': 'Acesso Negado',
    'admin.accessDeniedMessage': 'Você não tem permissão para acessar esta área.',
    'admin.loading': 'Carregando dados...',
    'admin.export': 'Exportar CSV',
    'admin.refresh': 'Atualizar',
    'admin.metrics.activeUsers': 'Usuários Ativos',
    'admin.metrics.canceledSubscriptions': 'Assinaturas Canceladas',
    'admin.metrics.failedPayments': 'Pagamentos Falharam',
    'admin.metrics.monthlyRevenue': 'Receita Mensal',
    'admin.tabs.users': 'Usuários',
    'admin.tabs.premiumUsers': 'Usuários Premium',
    'admin.tabs.essentialUsers': 'Usuários Essential',
    'admin.tabs.premiumAccess': 'Acesso Premium',
    'admin.tabs.alerts': 'Alertas',
    'admin.filters.title': 'Filtros',
    'admin.search.placeholder': 'Buscar por nome ou email...',
    'admin.filter.allStatus': 'Todos os Status',
    'admin.filter.active': 'Ativo',
    'admin.filter.overdue': 'Em Atraso',
    'admin.filter.canceled': 'Cancelado',
    'admin.filter.expired': 'Expirado',
    'admin.users.count': 'Usuários ({count})',
    'admin.table.userName': 'Nome do Usuário',
    'admin.table.email': 'Email',
    'admin.table.status': 'Status',
    'admin.table.plan': 'Plano',
    'admin.table.lastPayment': 'Último Pagamento',
    'admin.table.nextBilling': 'Próxima Cobrança',
    'admin.table.actions': 'Ações',
    'admin.status.active': 'Ativo',
    'admin.status.overdue': 'Em Atraso',
    'admin.status.canceled': 'Cancelado',
    'admin.status.expired': 'Expirado',
    'admin.action.view': 'Visualizar',
    'admin.action.notify': 'Notificar',
    'admin.action.reactivate': 'Reativar',
    'admin.alerts.title': 'Alertas do Sistema',
    'admin.alerts.subtitle': 'Eventos que requerem atenção',
    'admin.events.paymentFailed': 'Pagamento Falhado',
    'admin.events.subscriptionCanceled': 'Assinatura Cancelada',
    'admin.events.paymentConfirmed': 'Pagamento Confirmado',
    'admin.actions.sendNotification': 'Enviar Notificação',
    'admin.actions.offerReactivation': 'Oferecer Reativação',
    'admin.actions.noActionNeeded': 'Nenhuma Ação Necessária',
    'admin.actions.execute': 'Executar',
    'admin.loading.error': 'Erro ao carregar dados',
    'admin.notifications.sent': 'Notificação Enviada',
    'admin.notifications.sentMessage': 'Notificação enviada para {email}',
    'admin.reactivation.processed': 'Reativação Processada',
    'admin.reactivation.processedMessage': 'Oferta de reativação enviada para {email}',
    
    // Subscription
    'subscription.title': 'Planos e Assinaturas',
    'subscription.planActive': 'Plano Ativo:',
    'subscription.premiumAccess': 'Acesso completo aos recursos premium',
    'subscription.nextRenewal': 'Próxima renovação',
    'subscription.manageSubscription': 'Gerenciar Assinatura',
    'subscription.redirectingToPortal': 'Redirecionando para o portal...',
    'subscription.subscribeMonthly': 'Assinar Mensalmente',
    'subscription.subscribeAnnually': 'Assinar Anualmente',
    'subscription.redirectingToPayment': 'Redirecionando para pagamento...',
    'subscription.upgradeError': 'Erro ao processar upgrade',
    'subscription.portalError': 'Erro ao abrir portal de assinatura',
    'subscription.loading': 'Carregando...',
    'subscription.currentPlan': 'Seu Plano Atual',
    'subscription.plans.essential': 'Essencial',
    'subscription.plans.premium': 'Premium',
    'subscription.plans.essentialDescription': 'Recursos básicos para controle financeiro',
    'subscription.plans.premiumDescription': 'Recursos avançados com IA e automação',
    'subscription.current': 'Atual',
    'subscription.free': 'Gratuito',
    'subscription.month': 'mês',
    'subscription.year': 'ano',
    'subscription.annualDiscount': 'Com o plano anual você economiza aproximadamente 25%',
    'subscription.includesEssential': 'Inclui todos os recursos essenciais +',
    'subscription.whyPremium': 'Por que Premium?',
    'subscription.premiumBenefits': 'Vantagens exclusivas do plano premium',
    'subscription.upgradeRequired': 'Upgrade Necessário',
    'subscription.featureRequiresPremium': 'Este recurso requer o plano premium:',
    'subscription.unlockPremiumFeatures': 'Desbloqueie recursos premium',
    'subscription.recommended': 'Recomendado',
    'subscription.andMoreFeatures': 'E muito mais funcionalidades...',
    'subscription.maybeLater': 'Talvez Depois',
    
    // Recurring Expenses
    'recurring.title': 'Gastos Recorrentes',
    'recurring.addNew': 'Novo Gasto Recorrente',
    'recurring.editTitle': 'Editar Gasto Recorrente',
    'recurring.newTitle': 'Novo Gasto Recorrente',
    'recurring.name': 'Nome',
    'recurring.amount': 'Valor',
    'recurring.category': 'Categoria',
    'recurring.card': 'Cartão (Opcional)',
    'recurring.frequency': 'Frequência',
    'recurring.nextDue': 'Próximo Vencimento',
    'recurring.namePlaceholder': 'Ex: Netflix, Aluguel...',
    'recurring.amountPlaceholder': '0,00',
    'recurring.categoryPlaceholder': 'Selecione uma categoria',
    'recurring.cardPlaceholder': 'Selecione um cartão',
    'recurring.datePlaceholder': 'Selecione uma data',
    'recurring.weekly': 'Semanal (7 dias)',
    'recurring.monthly': 'Mensal (30 dias)',
    'recurring.quarterly': 'Trimestral (90 dias)',
    'recurring.yearly': 'Anual (365 dias)',
    'recurring.weeklyShort': 'Semanal',
    'recurring.monthlyShort': 'Mensal',
    'recurring.quarterlyShort': 'Trimestral',
    'recurring.yearlyShort': 'Anual',
    'recurring.everyDays': 'A cada {days} dias',
    'recurring.create': 'Criar',
    'recurring.update': 'Atualizar',
    'recurring.cancel': 'Cancelar',
    'recurring.activate': 'Ativar',
    'recurring.deactivate': 'Desativar',
    'recurring.active': 'Ativo',
    'recurring.inactive': 'Inativo',
    'recurring.next': 'Próximo',
    'recurring.noExpenses': 'Nenhum gasto recorrente cadastrado. Crie seu primeiro!',
    'recurring.success': 'Sucesso',
    'recurring.error': 'Erro',
    'recurring.created': 'Gasto recorrente criado!',
    'recurring.updated': 'Gasto recorrente atualizado!',
    'recurring.deleted': 'Gasto recorrente excluído!',
    'recurring.activated': 'Gasto recorrente ativado!',
    'recurring.deactivated': 'Gasto recorrente desativado!',
    'recurring.loadError': 'Não foi possível carregar gastos recorrentes',
    'recurring.saveError': 'Erro ao salvar gasto recorrente',
    'recurring.deleteError': 'Erro ao excluir gasto recorrente',
    'recurring.statusError': 'Erro ao alterar status',
    'recurring.userNotAuth': 'Usuário não autenticado',
    'subscription.upgradeToPremium': 'Fazer Upgrade para Premium',
    'subscription.features.aiFinancialPlanning': 'Planejamento financeiro com IA',
    'subscription.features.voiceInput': 'Input por voz via WhatsApp',
    'subscription.features.smartMiles': 'Sistema inteligente de milhagem',
    'subscription.features.advancedReports': 'Relatórios avançados',
    'subscription.features.prioritySupport': 'Suporte prioritário',
    'subscription.features.unlimitedGoals': 'Metas ilimitadas',
    'subscription.features.investmentTracking': 'Acompanhamento de investimentos',
    'subscription.features.multiCurrency': 'Múltiplas moedas',
    'subscription.features.basicFinancials': 'Controle financeiro básico',
    'subscription.features.jointAnalysis': 'Análise conjunta',
    'subscription.features.multiLanguage': 'Múltiplos idiomas',
    'subscription.features.investmentControl': 'Controle de investimentos',
    'subscription.features.manualMiles': 'Milhagem manual',
    'subscription.features.profitabilitySimulator': 'Simulador de rentabilidade',
    'subscription.features.basicSecurity': 'Segurança básica',
    'subscription.features.voiceWhatsApp': 'Input por voz via WhatsApp',
    'subscription.features.aiMiles': 'Sistema inteligente de milhagem com IA',
    'subscription.features.aiPlanning': 'Planejamento financeiro com IA',
    'subscription.features.personalizedInvestments': 'Investimentos personalizados',
    'subscription.features.customGoals': 'Metas personalizadas',
    'subscription.features.advancedAnalytics': 'Análises avançadas',
    'subscription.benefits.aiPowered': 'Recomendações personalizadas com IA',
    'subscription.benefits.smartRecommendations': 'Sugestões inteligentes de economia',
    'subscription.benefits.advancedReports': 'Relatórios detalhados e insights',
    'subscription.benefits.voiceWhatsapp': 'Controle por voz via WhatsApp',
    'subscription.benefits.voiceControl': 'Controle por voz via WhatsApp',
    'subscription.benefits.prioritySupport': 'Suporte prioritário',
    'subscription.benefits.unlimitedFeatures': 'Recursos ilimitados',
  },
  
  en: {
    // Hero Section
    'hero.badge': 'Launch',
    'hero.title': 'Couples Financials',
    'hero.subtitle': 'Control your finances intelligently',
    'hero.description': 'Designed for couples, but we recommend it for everyone. Plan, save and invest with AI help.',
    'hero.cta.free': 'Download for Free',
    'hero.cta.premium': 'Try AI version for $19.90',
    
    // Header
    'header.login': 'Sign in',
    'header.comingSoon': 'Feature coming soon.',
    
    // Benefits Section
    'benefits.title': 'Why choose',
    'benefits.subtitle': 'Innovative features for complete financial control',
    'benefits.shared.title': 'Shared or individual financial management',
    'benefits.shared.description': 'Control your finances alone or share with your partner',
    'benefits.multicurrency.title': 'Multi-currency control',
    'benefits.multicurrency.description': 'Manage expenses in different currencies with automatic conversion',
    'benefits.ai.title': 'AI intelligent planning',
    'benefits.ai.description': 'Know how much to save and where to invest with personalized recommendations',
    'benefits.miles.title': 'Smart miles tool',
    'benefits.miles.description': 'See promotions and use your miles intelligently',
    'benefits.voice.title': 'Voice input via WhatsApp',
    'benefits.voice.description': 'Talk to the bot and record your expenses without typing',
    'benefits.security.title': 'Security and privacy guaranteed',
    'benefits.security.description': 'Your financial data protected with advanced encryption',
    
    // Dashboard
    'dashboard.title': 'Financial Management for Couples',
    'dashboard.subtitle': 'Control your finances intelligently',
    'dashboard.balance': 'Total Balance',
    'dashboard.income': 'Income',
    'dashboard.expenses': 'Expenses',
    'dashboard.addTransaction': 'Add Transaction',
    'dashboard.viewMode': 'View Mode',
    'dashboard.both': 'Both',
    'dashboard.user1': 'User 1',
    'dashboard.user2': 'User 2',
    'dashboard.sharedActiveBanner': 'Shared dashboard active - showing data from both users',
    'dashboard.individualInviteBanner': 'Individual dashboard - invite your partner to share data',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Monthly Expenses',
    'nav.monthlyIncome': 'Monthly Income',
    'nav.categories': 'Categories',
    'nav.recurring': 'Recurring Expenses',
    'nav.cards': 'Cards',
    'nav.accounts': 'Accounts',
    'nav.profile': 'Profile',
    'nav.investments': 'Investments',
    'nav.mileage': 'Mileage',
    'nav.back': 'Back',
    'nav.admin': 'Admin',
    'nav.subscription': 'Plans',
    'nav.testEmail': 'Test Email',
    'nav.logout': 'Logout',
    
    // Cards
    'cards.title': 'Manage Cards',
    'cards.manage': 'Manage Cards',
    'cards.add': 'Add Card',
    'cards.name': 'Card Name',
    'cards.type': 'Card Type',
    'cards.credit': 'Credit',
    'cards.debit': 'Debit',
    'cards.lastFourDigits': 'Last 4 Digits',
    'cards.creditLimit': 'Credit Limit',
    'cards.currentBalance': 'Current Balance',
    'cards.currency': 'Currency',
    'cards.dueDate': 'Due Date',
    'cards.selectType': 'Select type',
    'cards.selectDay': 'Select day',
    'cards.adding': 'Adding...',
    'cards.addCard': 'Add Card',
    
    // Accounts
    'accounts.title': 'Manage Accounts',
    'accounts.manage': 'Manage Accounts',
    'accounts.add': 'Add Account',
    'accounts.name': 'Account Name',
    'accounts.type': 'Account Type',
    'accounts.types.checking': 'Checking Account',
    'accounts.types.savings': 'Savings',
    'accounts.types.investment': 'Investment',
    'accounts.types.other': 'Other',
    'accounts.models.personal': 'Personal',
    'accounts.models.business': 'Business',
    'accounts.yourAccounts': 'Your Accounts',
    'accounts.noAccounts': 'No accounts registered',
    'accounts.balance': 'Balance',
    'accounts.bank': 'Bank',
    'accounts.selectType': 'Select type',
    'accounts.adding': 'Adding...',
    'accounts.addAccount': 'Add Account',
    
    // Common
    'common.required': 'required',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'back': 'Back',
    
    // TransactionForm
    'transactionForm.title': 'New Transaction',
    'transactionForm.income': 'Income',
    'transactionForm.expense': 'Expense',
    'transactionForm.transactionDate': 'Transaction Date',
    'transactionForm.selectDate': 'Select date',
    'transactionForm.amount': 'Amount',
    'transactionForm.description': 'Description',
    'transactionForm.receiptMethod': 'Receipt Method',
    'transactionForm.paymentMethod': 'Payment Method',
    'transactionForm.selectPaymentMethod': 'Select method',
    'transactionForm.cash': 'Cash',
    'transactionForm.deposit': 'Deposit',
    'transactionForm.transfer': 'Transfer',
    'transactionForm.debitCard': 'Debit Card',
    'transactionForm.creditCard': 'Credit Card',
    'transactionForm.category': 'Category',
    'transactionForm.selectCategory': 'Select category',
    'transactionForm.subcategory': 'Subcategory',
    'transactionForm.currency': 'Currency',
    'transactionForm.addTransaction': 'Add Transaction',
    'transactionForm.paymentTransfer': 'Payment Transfer',
    'transactionForm.receivedTransfer': 'Received Transfer',
    'transactionForm.accountTransfer': 'Account Transfer',
    'transactionForm.accountInvestmentTransfer': 'Account-Investment Transfer',
    'transactionForm.selectAccount': 'Select Account',
    'transactionForm.selectAccountPlaceholder': 'Choose an account',
    'transactionForm.selectSourceAccount': 'Source Account',
    'transactionForm.selectDestinationAccount': 'Destination Account',
    'transactionForm.selectInvestment': 'Select Investment',
    
    // Auth
    'auth.appName': 'Couples Financials',
    'auth.tagline': 'Shared financial management for couples',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.tempPassword': 'Temporary Password',
    'auth.tempPasswordPlaceholder': 'Enter temporary password',
    'auth.name': 'Name',
    'auth.yourName': 'Your name',
    'auth.createAccount': 'Create Account',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetEmailSend': 'Send Recovery Email',
    'auth.backToLogin': 'Back to Login',
    'auth.inviteBanner': 'You have been invited! Use the temporary password sent by email.',
    'auth.loginSuccessTitle': 'Login successful!',
    'auth.loginSuccessDesc': 'Welcome back.',
    'auth.loginErrorTitle': 'Login error',
    'auth.loginErrorDesc': 'Check your credentials and try again.',
    'auth.googleErrorTitle': 'Google error',
    'auth.signupSuccessTitle': 'Account created successfully!',
    'auth.signupSuccessDesc': 'Check your email to confirm your account.',
    'auth.signupErrorTitle': 'Error creating account',
    'auth.signupErrorDesc': 'An error occurred. Please try again.',
    'auth.emailRequiredTitle': 'Email required',
    'auth.emailRequiredDesc': 'Please enter your email.',
    'auth.resetEmailTitle': 'Email sent!',
    'auth.resetEmailDesc': 'Check your inbox.',
    'auth.resetEmailErrorTitle': 'Error sending email',
    'auth.resetEmailErrorDesc': 'Please try again later.',
    
    // Categories
    'categories.title': 'Manage Categories',
    'categories.add': 'Add Category',
    'categories.edit': 'Edit Category',
    'categories.heading': 'Categories',
    'categories.name': 'Category Name',
    'categories.placeholder': 'Ex: Food, Transport...',
    'categories.color': 'Color',
    'categories.type': 'Type',
    'categories.type.expense': 'Expense',
    'categories.type.income': 'Income',
    'categories.filter.all': 'All Categories',
    'categories.filter.income': 'Income Categories',
    'categories.filter.expense': 'Expense Categories',
    'categories.create': 'Create',
    'categories.update': 'Update',
    'categories.none': 'No categories registered. Create your first category!',
    
    // Charts
    'charts.userAnalysisTitle': 'Financial Analysis by User',
    'charts.userComparison': 'User Comparison',
    'charts.expenses': 'Expenses',
    'charts.income': 'Income',
    'charts.currentMonth': 'Current Month',
    'charts.last3Months': '3 Months',
    'charts.last6Months': '6 Months',
    'charts.pieChart': 'Pie',
    'charts.barChart': 'Bar',
    'charts.total': 'Total',
    'charts.user1': 'User 1',
    'charts.user2': 'User 2',
    'charts.noData': 'No {type} found in period',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    
    // Messages
    'messages.cardAdded': 'Card added successfully!',
    'messages.cardError': 'Error adding card',
    'messages.accountAdded': 'Account added successfully!',
    'messages.accountError': 'Error loading account',
    'messages.accountDeleted': 'Account removed successfully!',
    'messages.accountDeleteError': 'Error removing account',
    'messages.categoryAdded': 'Category added successfully!',
    'messages.categoryError': 'Error adding category',
    'messages.transactionAdded': 'Transaction added successfully!',
    'messages.transactionError': 'Error adding transaction',
    'messages.duplicateAccountName': 'An account with this name already exists. Change and try again.',
    
    // Investments
    'investments.title': 'Investments',
    'investments.dashboard': 'Investment Dashboard',
    'investments.newInvestment': 'New Investment',
    'investments.totalInvested': 'Total Invested',
    'investments.currentValue': 'Current Value',
    'investments.totalReturn': 'Total Return',
    'investments.returnPercentage': 'Return %',
    'investments.distribution': 'Distribution by Type',
    'investments.name': 'Investment Name',
    'investments.type': 'Type',
    'investments.amount': 'Invested Amount',
    'investments.currentValueField': 'Current Value',
    'investments.purchaseDate': 'Purchase Date',
    'investments.broker': 'Broker',
    'investments.goal': 'Goal',
    'investments.currency': 'Currency',
    'investments.notes': 'Notes',
    'investments.isShared': 'Shared Investment',
    'investments.selectType': 'Select type',
    'investments.selectGoal': 'Select a goal',
    'investments.creating': 'Creating...',
    'investments.createInvestment': 'Create Investment',
    'investments.goals': 'Goals',
    'investments.overview': 'Overview',
    'investments.activeGoals': 'Active Goals',
    'investments.goalName': 'Goal Name',
    'investments.targetAmount': 'Target Amount',
    'investments.currentAmount': 'Current Amount',
    'investments.targetDate': 'Target Date',
    'investments.description': 'Description',
    'investments.completed': 'Completed',
    'investments.inProgress': 'In Progress',
    'investments.progress': 'Progress',
    'investments.profitabilitySimulator': 'Profitability Simulator',
    'investments.portfolioChart': 'Portfolio Chart',
    'investments.noInvestments': 'No investments found',
    'investments.noGoals': 'No goals found',
    'investments.noData': 'No data available',
    'investments.actions': 'Actions',
    'investments.date': 'Date',
    'investments.shared': 'Shared',
    'investments.listTitle': 'Investment List',
    'investments.addInvestment': 'Add Investment',
    
    // User Profile & Invites
    'userProfile.title': 'User Profile',
    'userProfile.profile': 'Profile',
    'userProfile.users': 'Users',
    'userProfile.billing': 'Billing',
    'userProfile.security': 'Security',
    'userProfile.personalInfo': 'Personal Information',
    'userProfile.email': 'Email',
    'userProfile.displayName': 'Display Name',
    'userProfile.preferredCurrency': 'Preferred Currency',
    'userProfile.saving': 'Saving...',
    'userProfile.saveProfile': 'Save Profile',
    'userProfile.userConfig': 'User Configuration',
    'userProfile.mainUser': 'Main User',
    'userProfile.secondUser': 'Second User',
    'userProfile.inviteEmail': 'Invite Email',
    'userProfile.sending': 'Sending...',
    'userProfile.sendInvite': 'Send Invite',
    'userProfile.saveSettings': 'Save Settings',
    'userProfile.billingInfo': 'Billing Information',
    'userProfile.freePlan': 'You are on the free plan',
    'userProfile.upgradeText': 'Upgrade to access premium features',
    'userProfile.upgradePlan': 'Upgrade Plan',
    'userProfile.changePassword': 'Change Password',
    'userProfile.newPassword': 'New Password',
    'userProfile.confirmPassword': 'Confirm Password',
    'userProfile.updating': 'Updating...',
    'userProfile.updatePassword': 'Update Password',
    
    // Invite Card
    'inviteCard': 'Invite Partner',
    'inviteSubtext': 'Share your finances',
    
    // Mileage
    'mileage.title': 'Mileage System',
    'mileage.subtitle': 'Manage your credit card miles and travel goals',
    'mileage.backToDashboard': 'Back to Dashboard',
    'mileage.totalMiles': 'Total Miles',
    'mileage.milesAccumulated': 'miles accumulated',
    'mileage.activeCards': 'Active Cards',
    'mileage.rulesConfigured': 'rules configured',
    'mileage.activeGoals': 'Active Goals',
    'mileage.inProgress': 'in progress',
    'mileage.rules': 'Mileage Rules',
    'mileage.goals': 'Goals',
    'mileage.history': 'History',
    'mileage.newRule': 'New Rule',
    'mileage.newGoal': 'New Goal',
    'mileage.ruleTitle': 'New Mileage Rule',
    'mileage.ruleDescription': 'Configure how miles are calculated for a specific card',
    'mileage.card': 'Card',
    'mileage.selectCard': 'Select a card',
    'mileage.bankName': 'Bank Name',
    'mileage.bankPlaceholder': 'Ex: Chase, Bank of America, Capital One',
    'mileage.cardBrand': 'Card Brand',
    'mileage.brandPlaceholder': 'Ex: Visa, Mastercard, American Express',
    'mileage.currency': 'Currency',
    'mileage.milesPerAmount': 'Miles per Amount',
    'mileage.milesPlaceholder': 'Ex: 1 (1 mile)',
    'mileage.amountThreshold': 'For every',
    'mileage.thresholdPlaceholder': 'Ex: 1 ($1.00 spent)',
    'mileage.createRule': 'Create Rule',
    'mileage.active': 'Active',
    'mileage.inactive': 'Inactive',
    'mileage.activate': 'Activate',
    'mileage.deactivate': 'Deactivate',
    'mileage.milesEarned': 'miles',
    'mileage.goalTitle': 'New Mileage Goal',
    'mileage.goalDescription': 'Set a goal to accumulate miles',
    'mileage.goalName': 'Goal Name',
    'mileage.goalNamePlaceholder': 'Ex: Trip to Europe',
    'mileage.targetMiles': 'Required Miles',
    'mileage.targetMilesPlaceholder': 'Ex: 50000',
    'mileage.targetDate': 'Target Date (Optional)',
    'mileage.description': 'Description (Optional)',
    'mileage.descriptionPlaceholder': 'Describe your goal...',
    'mileage.createGoal': 'Create Goal',
    'mileage.completed': 'Completed',
    'mileage.progressText': 'completed',
    'mileage.target': 'Target',
    'mileage.historyTitle': 'Mileage History',
    'mileage.spent': 'Spent',
    'mileage.ruleCreated': 'Mileage rule created successfully',
    'mileage.ruleCreateError': 'Error creating mileage rule',
    'mileage.goalCreated': 'Mileage goal created successfully',
    'mileage.goalCreateError': 'Error creating mileage goal',
    'mileage.ruleDeleted': 'Rule deleted successfully',
    'mileage.ruleDeleteError': 'Error deleting rule',
    'mileage.goalDeleted': 'Goal deleted successfully',
    'mileage.goalDeleteError': 'Error deleting goal',
    'mileage.ruleStatusError': 'Error updating rule status',
    
    // Admin
    'admin.title': 'Administrative Panel',
    'admin.subtitle': 'Manage system users and subscriptions',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedMessage': 'You do not have permission to access this area.',
    'admin.loading': 'Loading data...',
    'admin.export': 'Export CSV',
    'admin.refresh': 'Refresh',
    'admin.metrics.activeUsers': 'Active Users',
    'admin.metrics.canceledSubscriptions': 'Canceled Subscriptions',
    'admin.metrics.failedPayments': 'Failed Payments',
    'admin.metrics.monthlyRevenue': 'Monthly Revenue',
    'admin.tabs.users': 'Users',
    'admin.tabs.premiumUsers': 'Premium Users',
    'admin.tabs.essentialUsers': 'Essential Users',
    'admin.tabs.premiumAccess': 'Premium Access',
    'admin.tabs.alerts': 'Alerts',
    'admin.filters.title': 'Filters',
    'admin.search.placeholder': 'Search by name or email...',
    'admin.filter.allStatus': 'All Status',
    'admin.filter.active': 'Active',
    'admin.filter.overdue': 'Overdue',
    'admin.filter.canceled': 'Canceled',
    'admin.filter.expired': 'Expired',
    'admin.users.count': 'Users ({count})',
    'admin.table.userName': 'User Name',
    'admin.table.email': 'Email',
    'admin.table.status': 'Status',
    'admin.table.plan': 'Plan',
    'admin.table.lastPayment': 'Last Payment',
    'admin.table.nextBilling': 'Next Billing',
    'admin.table.actions': 'Actions',
    'admin.status.active': 'Active',
    'admin.status.overdue': 'Overdue',
    'admin.status.canceled': 'Canceled',
    'admin.status.expired': 'Expired',
    'admin.action.view': 'View',
    'admin.action.notify': 'Notify',
    'admin.action.reactivate': 'Reactivate',
    'admin.alerts.title': 'System Alerts',
    'admin.alerts.subtitle': 'Events that require attention',
    'admin.events.paymentFailed': 'Payment Failed',
    'admin.events.subscriptionCanceled': 'Subscription Canceled',
    'admin.events.paymentConfirmed': 'Payment Confirmed',
    'admin.actions.sendNotification': 'Send Notification',
    'admin.actions.offerReactivation': 'Offer Reactivation',
    'admin.actions.noActionNeeded': 'No Action Needed',
    'admin.actions.execute': 'Execute',
    'admin.loading.error': 'Error loading data',
    'admin.notifications.sent': 'Notification Sent',
    'admin.notifications.sentMessage': 'Notification sent to {email}',
    'admin.reactivation.processed': 'Reactivation Processed',
    'admin.reactivation.processedMessage': 'Reactivation offer sent to {email}',
    
    // Subscription
    'subscription.title': 'Plans and Subscriptions',
    'subscription.planActive': 'Active Plan:',
    'subscription.premiumAccess': 'Full access to premium features',
    'subscription.nextRenewal': 'Next renewal',
    'subscription.manageSubscription': 'Manage Subscription',
    'subscription.redirectingToPortal': 'Redirecting to portal...',
    'subscription.subscribeMonthly': 'Subscribe Monthly',
    'subscription.subscribeAnnually': 'Subscribe Annually',
    'subscription.redirectingToPayment': 'Redirecting to payment...',
    'subscription.upgradeError': 'Error processing upgrade',
    'subscription.portalError': 'Error opening subscription portal',
    'subscription.loading': 'Loading...',
    'subscription.currentPlan': 'Your Current Plan',
    'subscription.plans.essential': 'Essential',
    'subscription.plans.premium': 'Premium',
    'subscription.plans.essentialDescription': 'Basic features for financial control',
    'subscription.plans.premiumDescription': 'Advanced features with AI and automation',
    'subscription.current': 'Current',
    'subscription.free': 'Free',
    'subscription.month': 'month',
    'subscription.year': 'year',
    'subscription.annualDiscount': 'With the annual plan you get approximately 25% off',
    'subscription.includesEssential': 'Includes all essential features +',
    'subscription.whyPremium': 'Why Premium?',
    'subscription.premiumBenefits': 'Exclusive premium plan benefits',
    'subscription.upgradeRequired': 'Upgrade Required',
    'subscription.featureRequiresPremium': 'This feature requires premium plan:',
    'subscription.unlockPremiumFeatures': 'Unlock premium features',
    'subscription.recommended': 'Recommended',
    'subscription.andMoreFeatures': 'And many more features...',
    'subscription.maybeLater': 'Maybe Later',
    'subscription.upgradeToPremium': 'Upgrade to Premium',
    'subscription.features.aiFinancialPlanning': 'AI Financial Planning',
    'subscription.features.voiceInput': 'Voice input via WhatsApp',
    'subscription.features.smartMiles': 'Smart mileage system',
    'subscription.features.advancedReports': 'Advanced reports',
    'subscription.features.prioritySupport': 'Priority support',
    'subscription.features.unlimitedGoals': 'Unlimited goals',
    'subscription.features.investmentTracking': 'Investment tracking',
    'subscription.features.multiCurrency': 'Multi-currency',
    'subscription.features.basicFinancials': 'Basic financial control',
    'subscription.features.jointAnalysis': 'Joint analysis',
    'subscription.features.multiLanguage': 'Multiple languages',
    'subscription.features.investmentControl': 'Investment control',
    'subscription.features.manualMiles': 'Manual mileage',
    'subscription.features.profitabilitySimulator': 'Profitability simulator',
    'subscription.features.basicSecurity': 'Basic security',
    'subscription.features.voiceWhatsApp': 'Voice input via WhatsApp',
    'subscription.features.aiMiles': 'AI-powered smart mileage system',
    'subscription.features.aiPlanning': 'AI financial planning',
    'subscription.features.personalizedInvestments': 'Personalized investments',
    'subscription.features.customGoals': 'Custom goals',
    'subscription.features.advancedAnalytics': 'Advanced analytics',
    'subscription.benefits.aiPowered': 'Personalized AI recommendations',
    'subscription.benefits.smartRecommendations': 'Smart savings suggestions',
    'subscription.benefits.advancedReports': 'Detailed reports and insights',
    'subscription.benefits.voiceWhatsapp': 'Voice control via WhatsApp',
    'subscription.benefits.voiceControl': 'Voice control via WhatsApp',
    'subscription.benefits.prioritySupport': 'Priority support',
    'subscription.benefits.unlimitedFeatures': 'Unlimited features',
    
    // Recurring Expenses
    'recurring.title': 'Recurring Expenses',
    'recurring.addNew': 'New Recurring Expense',
    'recurring.editTitle': 'Edit Recurring Expense',
    'recurring.newTitle': 'New Recurring Expense',
    'recurring.name': 'Name',
    'recurring.amount': 'Amount',
    'recurring.category': 'Category',
    'recurring.card': 'Card (Optional)',
    'recurring.frequency': 'Frequency',
    'recurring.nextDue': 'Next Due Date',
    'recurring.namePlaceholder': 'Ex: Netflix, Rent...',
    'recurring.amountPlaceholder': '0.00',
    'recurring.categoryPlaceholder': 'Select a category',
    'recurring.cardPlaceholder': 'Select a card',
    'recurring.datePlaceholder': 'Select a date',
    'recurring.weekly': 'Weekly (7 days)',
    'recurring.monthly': 'Monthly (30 days)',
    'recurring.quarterly': 'Quarterly (90 days)',
    'recurring.yearly': 'Yearly (365 days)',
    'recurring.weeklyShort': 'Weekly',
    'recurring.monthlyShort': 'Monthly',
    'recurring.quarterlyShort': 'Quarterly',
    'recurring.yearlyShort': 'Yearly',
    'recurring.everyDays': 'Every {days} days',
    'recurring.create': 'Create',
    'recurring.update': 'Update',
    'recurring.cancel': 'Cancel',
    'recurring.activate': 'Activate',
    'recurring.deactivate': 'Deactivate',
    'recurring.active': 'Active',
    'recurring.inactive': 'Inactive',
    'recurring.next': 'Next',
    'recurring.noExpenses': 'No recurring expenses registered. Create your first one!',
    'recurring.success': 'Success',
    'recurring.error': 'Error',
    'recurring.created': 'Recurring expense created!',
    'recurring.updated': 'Recurring expense updated!',
    'recurring.deleted': 'Recurring expense deleted!',
    'recurring.activated': 'Recurring expense activated!',
    'recurring.deactivated': 'Recurring expense deactivated!',
    'recurring.loadError': 'Could not load recurring expenses',
    'recurring.saveError': 'Error saving recurring expense',
    'recurring.deleteError': 'Error deleting recurring expense',
    'recurring.statusError': 'Error changing status',
    'recurring.userNotAuth': 'User not authenticated',
  },
  
  es: {
    // Hero Section
    'hero.badge': 'Lanzamiento',
    'hero.title': 'Couples Financials',
    'hero.subtitle': 'Controla tus finanzas de forma inteligente',
    'hero.description': 'Diseñado para parejas, pero lo recomendamos para todos. Planifica, ahorra e invierte con ayuda de IA.',
    'hero.cta.free': 'Descargar Gratis',
    'hero.cta.premium': 'Prueba la versión con IA por $19.90',
    
    // Header
    'header.login': 'Iniciar sesión',
    'header.comingSoon': 'Funcionalidad próximamente.',
    
    // Benefits Section
    'benefits.title': 'Por qué elegir',
    'benefits.subtitle': 'Características innovadoras para control financiero completo',
    'benefits.shared.title': 'Gestión financiera compartida o individual',
    'benefits.shared.description': 'Controla tus finanzas solo o comparte con tu pareja',
    'benefits.multicurrency.title': 'Control en múltiples monedas',
    'benefits.multicurrency.description': 'Gestiona gastos en diferentes monedas con conversión automática',
    'benefits.ai.title': 'Planificación inteligente con IA',
    'benefits.ai.description': 'Sabe cuánto ahorrar y dónde invertir con recomendaciones personalizadas',
    'benefits.miles.title': 'Herramienta de millas inteligente',
    'benefits.miles.description': 'Ve promociones y usa tus millas con inteligencia',
    'benefits.voice.title': 'Entrada por voz vía WhatsApp',
    'benefits.voice.description': 'Habla con el bot y registra tus gastos sin escribir',
    'benefits.security.title': 'Seguridad y privacidad garantizadas',
    'benefits.security.description': 'Tus datos financieros protegidos con encriptación avanzada',
    
    // Dashboard
    'dashboard.title': 'Gestión Financiera para Parejas',
    'dashboard.subtitle': 'Controla tus finanzas de forma inteligente',
    'dashboard.balance': 'Saldo Total',
    'dashboard.income': 'Ingresos',
    'dashboard.expenses': 'Gastos',
    'dashboard.addTransaction': 'Agregar Transacción',
    'dashboard.viewMode': 'Modo de Vista',
    'dashboard.both': 'Ambos',
    'dashboard.user1': 'Usuario 1',
    'dashboard.user2': 'Usuario 2',
    'dashboard.sharedActiveBanner': 'Dashboard compartido activo - mostrando datos de ambos usuarios',
    'dashboard.individualInviteBanner': 'Dashboard individual - invita a tu pareja para compartir datos',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Gastos Mensuales',
    'nav.monthlyIncome': 'Ingresos Mensuales',
    'nav.categories': 'Categorías',
    'nav.recurring': 'Gastos Recurrentes',
    'nav.cards': 'Tarjetas',
    'nav.accounts': 'Cuentas',
    'nav.profile': 'Perfil',
    'nav.investments': 'Inversiones',
    'nav.mileage': 'Millaje',
    'nav.back': 'Atrás',
    'nav.admin': 'Admin',
    'nav.subscription': 'Planes',
    'nav.testEmail': 'Prueba Email',
    'nav.logout': 'Cerrar sesión',
    
    // Cards
    'cards.title': 'Gestionar Tarjetas',
    'cards.manage': 'Gestionar Tarjetas',
    'cards.add': 'Agregar Tarjeta',
    'cards.name': 'Nombre de Tarjeta',
    'cards.type': 'Tipo de Tarjeta',
    'cards.credit': 'Crédito',
    'cards.debit': 'Débito',
    'cards.lastFourDigits': 'Últimos 4 Dígitos',
    'cards.creditLimit': 'Límite de Crédito',
    'cards.currentBalance': 'Saldo Actual',
    'cards.currency': 'Moneda',
    'cards.dueDate': 'Fecha de Vencimiento',
    'cards.selectType': 'Seleccionar tipo',
    'cards.selectDay': 'Seleccionar día',
    'cards.adding': 'Agregando...',
    'cards.addCard': 'Agregar Tarjeta',
    
    // Accounts
    'accounts.title': 'Gestionar Cuentas',
    'accounts.manage': 'Gestionar Cuentas',
    'accounts.add': 'Agregar Cuenta',
    'accounts.name': 'Nombre de Cuenta',
    'accounts.type': 'Tipo de Cuenta',
    'accounts.types.checking': 'Cuenta Corriente',
    'accounts.types.savings': 'Ahorros',
    'accounts.types.investment': 'Inversión',
    'accounts.types.other': 'Otra',
    'accounts.models.personal': 'Personal',
    'accounts.models.business': 'Empresarial',
    'accounts.yourAccounts': 'Tus Cuentas',
    'accounts.noAccounts': 'No hay cuentas registradas',
    'accounts.balance': 'Saldo',
    'accounts.bank': 'Banco',
    'accounts.selectType': 'Seleccionar tipo',
    'accounts.adding': 'Agregando...',
    'accounts.addAccount': 'Agregar Cuenta',
    
    // Common
    'common.required': 'requerido',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.loading': 'Cargando...',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.select': 'Seleccionar',
    'back': 'Atrás',
    
    // TransactionForm
    'transactionForm.title': 'Nueva Transacción',
    'transactionForm.income': 'Ingreso',
    'transactionForm.expense': 'Gasto',
    'transactionForm.transactionDate': 'Fecha de Transacción',
    'transactionForm.selectDate': 'Seleccionar fecha',
    'transactionForm.amount': 'Cantidad',
    'transactionForm.description': 'Descripción',
    'transactionForm.receiptMethod': 'Método de Recibo',
    'transactionForm.paymentMethod': 'Método de Pago',
    'transactionForm.selectPaymentMethod': 'Seleccionar método',
    'transactionForm.cash': 'Efectivo',
    'transactionForm.deposit': 'Depósito',
    'transactionForm.transfer': 'Transferencia',
    'transactionForm.debitCard': 'Tarjeta de Débito',
    'transactionForm.creditCard': 'Tarjeta de Crédito',
    'transactionForm.category': 'Categoría',
    'transactionForm.selectCategory': 'Seleccionar categoría',
    'transactionForm.subcategory': 'Subcategoría',
    'transactionForm.currency': 'Moneda',
    'transactionForm.addTransaction': 'Agregar Transacción',
    'transactionForm.paymentTransfer': 'Transferencia de Pago',
    'transactionForm.receivedTransfer': 'Transferencia Recibida',
    'transactionForm.accountTransfer': 'Transferencia entre Cuentas',
    'transactionForm.accountInvestmentTransfer': 'Transferencia Cuenta-Inversión',
    'transactionForm.selectAccount': 'Seleccionar Cuenta',
    'transactionForm.selectAccountPlaceholder': 'Elige una cuenta',
    'transactionForm.selectSourceAccount': 'Cuenta de Origen',
    'transactionForm.selectDestinationAccount': 'Cuenta de Destino',
    'transactionForm.selectInvestment': 'Seleccionar Inversión',
    
    // Auth
    'auth.appName': 'Couples Financials',
    'auth.tagline': 'Gestión financiera compartida para parejas',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.password': 'Contraseña',
    'auth.tempPassword': 'Contraseña Temporal',
    'auth.tempPasswordPlaceholder': 'Ingresa la contraseña temporal',
    'auth.name': 'Nombre',
    'auth.yourName': 'Tu nombre',
    'auth.createAccount': 'Crear Cuenta',
    'auth.continueWithGoogle': 'Continuar con Google',
    'auth.forgotPassword': '¿Olvidaste la contraseña?',
    'auth.resetEmailSend': 'Enviar Email de Recuperación',
    'auth.backToLogin': 'Volver al Inicio de Sesión',
    'auth.inviteBanner': '¡Has sido invitado! Usa la contraseña temporal enviada por email.',
    'auth.loginSuccessTitle': '¡Inicio de sesión exitoso!',
    'auth.loginSuccessDesc': 'Bienvenido de vuelta.',
    'auth.loginErrorTitle': 'Error en el inicio de sesión',
    'auth.loginErrorDesc': 'Verifica tus credenciales e intenta nuevamente.',
    'auth.googleErrorTitle': 'Error de Google',
    'auth.signupSuccessTitle': '¡Cuenta creada exitosamente!',
    'auth.signupSuccessDesc': 'Revisa tu email para confirmar tu cuenta.',
    'auth.signupErrorTitle': 'Error al crear cuenta',
    'auth.signupErrorDesc': 'Ocurrió un error. Inténtalo nuevamente.',
    'auth.emailRequiredTitle': 'Email requerido',
    'auth.emailRequiredDesc': 'Por favor, ingresa tu email.',
    'auth.resetEmailTitle': '¡Email enviado!',
    'auth.resetEmailDesc': 'Revisa tu bandeja de entrada.',
    'auth.resetEmailErrorTitle': 'Error al enviar email',
    'auth.resetEmailErrorDesc': 'Inténtalo nuevamente más tarde.',
    
    // Categories
    'categories.title': 'Gestionar Categorías',
    'categories.add': 'Agregar Categoría',
    'categories.edit': 'Editar Categoría',
    'categories.heading': 'Categorías',
    'categories.name': 'Nombre de Categoría',
    'categories.placeholder': 'Ej: Comida, Transporte...',
    'categories.color': 'Color',
    'categories.type': 'Tipo',
    'categories.type.expense': 'Gasto',
    'categories.type.income': 'Ingreso',
    'categories.filter.all': 'Todas las Categorías',
    'categories.filter.income': 'Categorías de Ingreso',
    'categories.filter.expense': 'Categorías de Gasto',
    'categories.create': 'Crear',
    'categories.update': 'Actualizar',
    'categories.none': 'No hay categorías registradas. ¡Crea tu primera categoría!',
    
    // Charts
    'charts.userAnalysisTitle': 'Análisis Financiero por Usuario',
    'charts.userComparison': 'Comparación de Usuarios',
    'charts.expenses': 'Gastos',
    'charts.income': 'Ingresos',
    'charts.currentMonth': 'Mes Actual',
    'charts.last3Months': '3 Meses',
    'charts.last6Months': '6 Meses',
    'charts.pieChart': 'Pastel',
    'charts.barChart': 'Barras',
    'charts.total': 'Total',
    'charts.user1': 'Usuario 1',
    'charts.user2': 'Usuario 2',
    'charts.noData': 'No se encontraron {type} en el período',
    
    // Theme
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    
    // Messages
    'messages.cardAdded': '¡Tarjeta agregada exitosamente!',
    'messages.cardError': 'Error al agregar tarjeta',
    'messages.accountAdded': '¡Cuenta agregada exitosamente!',
    'messages.accountError': 'Error al cargar cuenta',
    'messages.accountDeleted': '¡Cuenta eliminada exitosamente!',
    'messages.accountDeleteError': 'Error al eliminar cuenta',
    'messages.categoryAdded': '¡Categoría agregada exitosamente!',
    'messages.categoryError': 'Error al agregar categoría',
    'messages.transactionAdded': '¡Transacción agregada exitosamente!',
    'messages.transactionError': 'Error al agregar transacción',
    'messages.duplicateAccountName': 'Ya existe una cuenta con este nombre. Cambia e intenta de nuevo.',
    
    // Investments
    'investments.title': 'Inversiones',
    'investments.dashboard': 'Dashboard de Inversiones',
    'investments.newInvestment': 'Nueva Inversión',
    'investments.totalInvested': 'Total Invertido',
    'investments.currentValue': 'Valor Actual',
    'investments.totalReturn': 'Retorno Total',
    'investments.returnPercentage': 'Retorno %',
    'investments.distribution': 'Distribución por Tipo',
    'investments.name': 'Nombre de Inversión',
    'investments.type': 'Tipo',
    'investments.amount': 'Cantidad Invertida',
    'investments.currentValueField': 'Valor Actual',
    'investments.purchaseDate': 'Fecha de Compra',
    'investments.broker': 'Corredor',
    'investments.goal': 'Meta',
    'investments.currency': 'Moneda',
    'investments.notes': 'Notas',
    'investments.isShared': 'Inversión Compartida',
    'investments.selectType': 'Seleccionar tipo',
    'investments.selectGoal': 'Seleccionar una meta',
    'investments.creating': 'Creando...',
    'investments.createInvestment': 'Crear Inversión',
    'investments.goals': 'Objetivos',
    'investments.overview': 'Resumen',
    'investments.activeGoals': 'Objetivos Activos',
    'investments.goalName': 'Nombre del Objetivo',
    'investments.targetAmount': 'Cantidad Objetivo',
    'investments.currentAmount': 'Cantidad Actual',
    'investments.targetDate': 'Fecha Objetivo',
    'investments.description': 'Descripción',
    'investments.completed': 'Completado',
    'investments.inProgress': 'En Progreso',
    'investments.progress': 'Progreso',
    'investments.profitabilitySimulator': 'Simulador de Rentabilidad',
    'investments.portfolioChart': 'Gráfico de Portafolio',
    'investments.noInvestments': 'No se encontraron inversiones',
    'investments.noGoals': 'No se encontraron objetivos',
    'investments.noData': 'No hay datos disponibles',
    'investments.actions': 'Acciones',
    'investments.date': 'Fecha',
    'investments.shared': 'Compartido',
    'investments.listTitle': 'Lista de Inversiones',
    'investments.addInvestment': 'Agregar Inversión',
    
    // User Profile & Invites
    'userProfile.title': 'Perfil de Usuario',
    'userProfile.profile': 'Perfil',
    'userProfile.users': 'Usuarios',
    'userProfile.billing': 'Facturación',
    'userProfile.security': 'Seguridad',
    'userProfile.personalInfo': 'Información Personal',
    'userProfile.email': 'Email',
    'userProfile.displayName': 'Nombre de Visualización',
    'userProfile.preferredCurrency': 'Moneda Preferida',
    'userProfile.saving': 'Guardando...',
    'userProfile.saveProfile': 'Guardar Perfil',
    'userProfile.userConfig': 'Configuración de Usuario',
    'userProfile.mainUser': 'Usuario Principal',
    'userProfile.secondUser': 'Segundo Usuario',
    'userProfile.inviteEmail': 'Email de Invitación',
    'userProfile.sending': 'Enviando...',
    'userProfile.sendInvite': 'Enviar Invitación',
    'userProfile.saveSettings': 'Guardar Configuraciones',
    'userProfile.billingInfo': 'Información de Facturación',
    'userProfile.freePlan': 'Estás en el plan gratuito',
    'userProfile.upgradeText': 'Actualiza para acceder a características premium',
    'userProfile.upgradePlan': 'Actualizar Plan',
    'userProfile.changePassword': 'Cambiar Contraseña',
    'userProfile.newPassword': 'Nueva Contraseña',
    'userProfile.confirmPassword': 'Confirmar Contraseña',
    'userProfile.updating': 'Actualizando...',
    'userProfile.updatePassword': 'Actualizar Contraseña',
    
    // Invite Card
    'inviteCard': 'Invitar Pareja',
    'inviteSubtext': 'Comparte tus finanzas',
    
    // Mileage
    'mileage.title': 'Sistema de Millaje',
    'mileage.subtitle': 'Gestiona tus millas de tarjeta de crédito y metas de viaje',
    'mileage.backToDashboard': 'Volver al Dashboard',
    'mileage.totalMiles': 'Total de Millas',
    'mileage.milesAccumulated': 'millas acumuladas',
    'mileage.activeCards': 'Tarjetas Activas',
    'mileage.rulesConfigured': 'reglas configuradas',
    'mileage.activeGoals': 'Metas Activas',
    'mileage.inProgress': 'en progreso',
    'mileage.rules': 'Reglas de Millaje',
    'mileage.goals': 'Metas',
    'mileage.history': 'Historial',
    'mileage.newRule': 'Nueva Regla',
    'mileage.newGoal': 'Nueva Meta',
    'mileage.ruleTitle': 'Nueva Regla de Millaje',
    'mileage.ruleDescription': 'Configura cómo se calculan las millas para una tarjeta específica',
    'mileage.card': 'Tarjeta',
    'mileage.selectCard': 'Selecciona una tarjeta',
    'mileage.bankName': 'Nombre del Banco',
    'mileage.bankPlaceholder': 'Ej: BBVA, Santander, Citibank',
    'mileage.cardBrand': 'Marca de Tarjeta',
    'mileage.brandPlaceholder': 'Ej: Visa, Mastercard, American Express',
    'mileage.currency': 'Moneda',
    'mileage.milesPerAmount': 'Millas por Cantidad',
    'mileage.milesPlaceholder': 'Ej: 1 (1 milla)',
    'mileage.amountThreshold': 'Por cada',
    'mileage.thresholdPlaceholder': 'Ej: 1 ($1.00 gastados)',
    'mileage.createRule': 'Crear Regla',
    'mileage.active': 'Activo',
    'mileage.inactive': 'Inactivo',
    'mileage.activate': 'Activar',
    'mileage.deactivate': 'Desactivar',
    'mileage.milesEarned': 'millas',
    'mileage.goalTitle': 'Nueva Meta de Millaje',
    'mileage.goalDescription': 'Establece una meta para acumular millas',
    'mileage.goalName': 'Nombre de la Meta',
    'mileage.goalNamePlaceholder': 'Ej: Viaje a Europa',
    'mileage.targetMiles': 'Millas Necesarias',
    'mileage.targetMilesPlaceholder': 'Ej: 50000',
    'mileage.targetDate': 'Fecha Meta (Opcional)',
    'mileage.description': 'Descripción (Opcional)',
    'mileage.descriptionPlaceholder': 'Describe tu meta...',
    'mileage.createGoal': 'Crear Meta',
    'mileage.completed': 'Completada',
    'mileage.progressText': 'completado',
    'mileage.target': 'Meta',
    'mileage.historyTitle': 'Historial de Millaje',
    'mileage.spent': 'Gastado',
    'mileage.ruleCreated': 'Regla de millaje creada exitosamente',
    'mileage.ruleCreateError': 'Error al crear regla de millaje',
    'mileage.goalCreated': 'Meta de millaje creada exitosamente',
    'mileage.goalCreateError': 'Error al crear meta de millaje',
    'mileage.ruleDeleted': 'Regla eliminada exitosamente',
    'mileage.ruleDeleteError': 'Error al eliminar regla',
    'mileage.goalDeleted': 'Meta eliminada exitosamente',
    'mileage.goalDeleteError': 'Error al eliminar meta',
    'mileage.ruleStatusError': 'Error al actualizar estado de la regla',
    
    // Admin
    'admin.title': 'Panel Administrativo',
    'admin.subtitle': 'Gestionar usuarios y suscripciones del sistema',
    'admin.accessDenied': 'Acceso Denegado',
    'admin.accessDeniedMessage': 'No tienes permiso para acceder a esta área.',
    'admin.loading': 'Cargando datos...',
    'admin.export': 'Exportar CSV',
    'admin.refresh': 'Actualizar',
    'admin.metrics.activeUsers': 'Usuarios Activos',
    'admin.metrics.canceledSubscriptions': 'Suscripciones Canceladas',
    'admin.metrics.failedPayments': 'Pagos Fallidos',
    'admin.metrics.monthlyRevenue': 'Ingresos Mensuales',
    'admin.tabs.users': 'Usuarios',
    'admin.tabs.premiumUsers': 'Usuarios Premium',
    'admin.tabs.essentialUsers': 'Usuarios Essential',
    'admin.tabs.premiumAccess': 'Acceso Premium',
    'admin.tabs.alerts': 'Alertas',
    'admin.filters.title': 'Filtros',
    'admin.search.placeholder': 'Buscar por nombre o email...',
    'admin.filter.allStatus': 'Todos los Estados',
    'admin.filter.active': 'Activo',
    'admin.filter.overdue': 'Vencido',
    'admin.filter.canceled': 'Cancelado',
    'admin.filter.expired': 'Expirado',
    'admin.users.count': 'Usuarios ({count})',
    'admin.table.userName': 'Nombre de Usuario',
    'admin.table.email': 'Email',
    'admin.table.status': 'Estado',
    'admin.table.plan': 'Plan',
    'admin.table.lastPayment': 'Último Pago',
    'admin.table.nextBilling': 'Próxima Facturación',
    'admin.table.actions': 'Acciones',
    'admin.status.active': 'Activo',
    'admin.status.overdue': 'Vencido',
    'admin.status.canceled': 'Cancelado',
    'admin.status.expired': 'Expirado',
    'admin.action.view': 'Ver',
    'admin.action.notify': 'Notificar',
    'admin.action.reactivate': 'Reactivar',
    'admin.alerts.title': 'Alertas del Sistema',
    'admin.alerts.subtitle': 'Eventos que requieren atención',
    'admin.events.paymentFailed': 'Pago Fallido',
    'admin.events.subscriptionCanceled': 'Suscripción Cancelada',
    'admin.events.paymentConfirmed': 'Pago Confirmado',
    'admin.actions.sendNotification': 'Enviar Notificación',
    'admin.actions.offerReactivation': 'Ofrecer Reactivación',
    'admin.actions.noActionNeeded': 'No se Requiere Acción',
    'admin.actions.execute': 'Ejecutar',
    'admin.loading.error': 'Error al cargar datos',
    'admin.notifications.sent': 'Notificación Enviada',
    'admin.notifications.sentMessage': 'Notificación enviada a {email}',
    'admin.reactivation.processed': 'Reactivación Procesada',
    'admin.reactivation.processedMessage': 'Oferta de reactivación enviada a {email}',
    
    // Subscription
    'subscription.title': 'Planes y Suscripciones',
    'subscription.planActive': 'Plan Activo:',
    'subscription.premiumAccess': 'Acceso completo a características premium',
    'subscription.nextRenewal': 'Próxima renovación',
    'subscription.manageSubscription': 'Gestionar Suscripción',
    'subscription.redirectingToPortal': 'Redirigiendo al portal...',
    'subscription.subscribeMonthly': 'Suscribirse Mensualmente',
    'subscription.subscribeAnnually': 'Suscribirse Anualmente',
    'subscription.redirectingToPayment': 'Redirigiendo al pago...',
    'subscription.upgradeError': 'Error al procesar actualización',
    'subscription.portalError': 'Error al abrir portal de suscripción',
    'subscription.loading': 'Cargando...',
    'subscription.currentPlan': 'Tu Plan Actual',
    'subscription.plans.essential': 'Esencial',
    'subscription.plans.premium': 'Premium',
    'subscription.plans.essentialDescription': 'Características básicas para control financiero',
    'subscription.plans.premiumDescription': 'Características avanzadas con IA y automatización',
    'subscription.current': 'Actual',
    'subscription.free': 'Gratuito',
    'subscription.month': 'mes',
    'subscription.year': 'año',
    'subscription.annualDiscount': 'Con el plan anual obtienes aproximadamente 25% de descuento',
    'subscription.includesEssential': 'Incluye todas las características esenciales +',
    'subscription.whyPremium': '¿Por qué Premium?',
    'subscription.premiumBenefits': 'Beneficios exclusivos del plan premium',
    'subscription.upgradeRequired': 'Actualización Requerida',
    'subscription.featureRequiresPremium': 'Esta característica requiere plan premium:',
    'subscription.unlockPremiumFeatures': 'Desbloquear características premium',
    'subscription.recommended': 'Recomendado',
    'subscription.andMoreFeatures': 'Y muchas más funcionalidades...',
    'subscription.maybeLater': 'Tal vez Después',
    'subscription.upgradeToPremium': 'Actualizar a Premium',
    'subscription.features.aiFinancialPlanning': 'Planificación financiera con IA',
    'subscription.features.voiceInput': 'Entrada por voz vía WhatsApp',
    'subscription.features.smartMiles': 'Sistema inteligente de millaje',
    'subscription.features.advancedReports': 'Reportes avanzados',
    'subscription.features.prioritySupport': 'Soporte prioritario',
    'subscription.features.unlimitedGoals': 'Metas ilimitadas',
    'subscription.features.investmentTracking': 'Seguimiento de inversiones',
    'subscription.features.multiCurrency': 'Múltiples monedas',
    'subscription.features.basicFinancials': 'Control financiero básico',
    'subscription.features.jointAnalysis': 'Análisis conjunto',
    'subscription.features.multiLanguage': 'Múltiples idiomas',
    'subscription.features.investmentControl': 'Control de inversiones',
    'subscription.features.manualMiles': 'Millaje manual',
    'subscription.features.profitabilitySimulator': 'Simulador de rentabilidad',
    'subscription.features.basicSecurity': 'Seguridad básica',
    'subscription.features.voiceWhatsApp': 'Entrada por voz vía WhatsApp',
    'subscription.features.aiMiles': 'Sistema inteligente de millaje con IA',
    'subscription.features.aiPlanning': 'Planificación financiera con IA',
    'subscription.features.personalizedInvestments': 'Inversiones personalizadas',
    'subscription.features.customGoals': 'Metas personalizadas',
    'subscription.features.advancedAnalytics': 'Análisis avanzados',
    'subscription.benefits.aiPowered': 'Recomendaciones personalizadas con IA',
    'subscription.benefits.smartRecommendations': 'Sugerencias inteligentes de ahorro',
    'subscription.benefits.advancedReports': 'Reportes detallados e insights',
    'subscription.benefits.voiceWhatsapp': 'Control por voz vía WhatsApp',
    'subscription.benefits.voiceControl': 'Control por voz vía WhatsApp',
    'subscription.benefits.prioritySupport': 'Soporte prioritario',
    'subscription.benefits.unlimitedFeatures': 'Funcionalidades ilimitadas',
    
    // Recurring Expenses
    'recurring.title': 'Gastos Recurrentes',
    'recurring.addNew': 'Nuevo Gasto Recurrente',
    'recurring.editTitle': 'Editar Gasto Recurrente',
    'recurring.newTitle': 'Nuevo Gasto Recurrente',
    'recurring.name': 'Nombre',
    'recurring.amount': 'Valor',
    'recurring.category': 'Categoría',
    'recurring.card': 'Tarjeta (Opcional)',
    'recurring.frequency': 'Frecuencia',
    'recurring.nextDue': 'Próximo Vencimiento',
    'recurring.namePlaceholder': 'Ej: Netflix, Alquiler...',
    'recurring.amountPlaceholder': '0,00',
    'recurring.categoryPlaceholder': 'Selecciona una categoría',
    'recurring.cardPlaceholder': 'Selecciona una tarjeta',
    'recurring.datePlaceholder': 'Selecciona una fecha',
    'recurring.weekly': 'Semanal (7 días)',
    'recurring.monthly': 'Mensual (30 días)',
    'recurring.quarterly': 'Trimestral (90 días)',
    'recurring.yearly': 'Anual (365 días)',
    'recurring.weeklyShort': 'Semanal',
    'recurring.monthlyShort': 'Mensual',
    'recurring.quarterlyShort': 'Trimestral',
    'recurring.yearlyShort': 'Anual',
    'recurring.everyDays': 'Cada {days} días',
    'recurring.create': 'Crear',
    'recurring.update': 'Actualizar',
    'recurring.cancel': 'Cancelar',
    'recurring.activate': 'Activar',
    'recurring.deactivate': 'Desactivar',
    'recurring.active': 'Activo',
    'recurring.inactive': 'Inactivo',
    'recurring.next': 'Próximo',
    'recurring.noExpenses': 'Ningún gasto recurrente registrado. ¡Crea tu primero!',
    'recurring.success': 'Éxito',
    'recurring.error': 'Error',
    'recurring.created': '¡Gasto recurrente creado!',
    'recurring.updated': '¡Gasto recurrente actualizado!',
    'recurring.deleted': '¡Gasto recurrente eliminado!',
    'recurring.activated': '¡Gasto recurrente activado!',
    'recurring.deactivated': '¡Gasto recurrente desactivado!',
    'recurring.loadError': 'No se pudieron cargar los gastos recurrentes',
    'recurring.saveError': 'Error al guardar gasto recurrente',
    'recurring.deleteError': 'Error al eliminar gasto recurrente',
    'recurring.statusError': 'Error al cambiar estado',
    'recurring.userNotAuth': 'Usuario no autenticado',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [languageState, setLanguageState] = useState<Language>('pt');
  const [inBrazil, setInBrazil] = useState<boolean>(true);
  const [userPreferred, setUserPreferred] = useState<boolean>(false);

  // Persisted setter that marks user preference
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setUserPreferred(true);
    try {
      localStorage.setItem('language', lang);
    } catch {}
  };

  // Initialize language and detect location
  useEffect(() => {
    try {
      const stored = localStorage.getItem('language') as Language | null;
      if (stored) {
        setLanguageState(stored);
        setUserPreferred(true);
      } else {
        const nav = navigator.language || (Array.isArray(navigator.languages) ? navigator.languages[0] : 'en');
        const defaultLang: Language = nav?.startsWith('pt') ? 'pt' : nav?.startsWith('es') ? 'es' : 'en';
        setLanguageState(defaultLang);
      }
    } catch {}

    // Geo-IP detection (fallback to timezone heuristics)
    fetch('https://ipapi.co/json/')
      .then((res) => (res.ok ? res.json() : Promise.reject('geo fetch failed')))
      .then((data) => {
        const isBR = data?.country_code === 'BR';
        setInBrazil(!!isBR);
        if (!isBR && !userPreferred) {
          setLanguageState('en');
        }
      })
      .catch(() => {
        try {
          const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
          const isBR = tz.includes('Sao_Paulo') || tz.includes('America/Sao_Paulo') || tz.includes('America/Fortaleza') || tz.includes('America/Recife') || tz.includes('America/Manaus');
          setInBrazil(isBR);
        } catch {
          setInBrazil(true);
        }
      });
  }, []);

  const t = (key: string): string => {
    return translations[languageState]?.[key] || key;
  };

  const tFor = (lang: Language, key: string): string => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: languageState, setLanguage, t, tFor, inBrazil }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}