import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'pt' | 'en';
  setLanguage: (lang: 'pt' | 'en') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Dashboard
    'dashboard.title': 'Gestão Financeira para Casais',
    'dashboard.subtitle': 'Controle suas finanças de forma inteligente',
    'dashboard.balance': 'Saldo Total',
    'dashboard.income': 'Receitas',
    'dashboard.expenses': 'Despesas',
    'dashboard.addTransaction': 'Adicionar Transação',
    'dashboard.viewMode': 'Modo de Visualização',
    'dashboard.both': 'Ambos',
    'dashboard.user1': 'Usuário 1',
    'dashboard.user2': 'Usuário 2',
    'dashboard.vsPreviousMonth': 'vs mês anterior',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Gastos Mensais',
    'nav.categories': 'Categorias',
    'nav.recurring': 'Gastos Recorrentes',
    'nav.cards': 'Cartões',
    'nav.accounts': 'Contas',
    'nav.profile': 'Perfil',
    'nav.investments': 'Investimentos',
    'nav.mileage': 'Milhagem',
    'nav.back': 'Voltar',
    
    // Transactions
    'transaction.add': 'Adicionar Transação',
    'transaction.type': 'Tipo',
    'transaction.income': 'Receita',
    'transaction.expense': 'Despesa',
    'transaction.amount': 'Valor',
    'transaction.description': 'Descrição',
    'transaction.category': 'Categoria',
    'transaction.date': 'Data',
    'transaction.paymentMethod': 'Método de Pagamento',
    'transaction.cash': 'Dinheiro',
    'transaction.creditCard': 'Cartão de Crédito',
    'transaction.debitCard': 'Cartão de Débito',
    'transaction.bankTransfer': 'Transferência Bancária',
    'transaction.pix': 'PIX',
    'transaction.submit': 'Adicionar',
    'transaction.submitting': 'Adicionando...',
    
    // TransactionForm specific translations
    'transactionForm.title': 'Nova Transação',
    'transactionForm.income': 'Receita',
    'transactionForm.expense': 'Despesa',
    'transactionForm.transactionDate': 'Data da Transação',
    'transactionForm.selectDate': 'Selecionar data',
    'transactionForm.amount': 'Valor',
    'transactionForm.description': 'Descrição',
    'transactionForm.receiptMethod': 'Método de Recebimento',
    'transactionForm.paymentMethod': 'Método de Pagamento',
    'transactionForm.selectPaymentMethod': 'Selecionar método',
    'transactionForm.cash': 'Dinheiro',
    'transactionForm.deposit': 'Depósito',
    'transactionForm.transfer': 'Transferência',
    'transactionForm.debitCard': 'Cartão de Débito',
    'transactionForm.creditCard': 'Cartão de Crédito',
    'transactionForm.card': 'Cartão',
    'transactionForm.selectCard': 'Selecionar cartão',
    'transactionForm.selectCardPlaceholder': 'Selecione o cartão',
    'transactionForm.account': 'Conta Bancária',
    'transactionForm.selectAccount': 'Selecione a conta',
    'transactionForm.selectAccountPlaceholder': 'Selecione a conta',
    'transactionForm.installmentPayment': 'Pagamento parcelado',
    'transactionForm.installments': 'Parcelas',
    'transactionForm.selectInstallments': 'Selecionar parcelas',
    'transactionForm.category': 'Categoria',
    'transactionForm.selectCategory': 'Selecionar categoria',
    'transactionForm.subcategory': 'Subcategoria',
    'transactionForm.currency': 'Moeda',
    'transactionForm.addTransaction': 'Adicionar Transação',
    
    // Cards
    'cards.title': 'Gerenciar Cartões',
    'cards.manage': 'Gerenciar Cartões',
    'cards.add': 'Adicionar Cartão',
    'cards.name': 'Nome do Cartão',
    'cards.type': 'Tipo do Cartão',
    'cards.credit': 'Crédito',
    'cards.debit': 'Débito',
    'cards.lastFourDigits': 'Últimos 4 Dígitos',
    'cards.creditLimit': 'Limite de Crédito',
    'cards.currentBalance': 'Saldo Atual',
    'cards.currency': 'Moeda',
    'cards.dueDate': 'Data de Vencimento',
    'cards.selectType': 'Selecione o tipo',
    'cards.selectDay': 'Selecione o dia',
    'cards.adding': 'Adicionando...',
    'cards.addCard': 'Adicionar Cartão',
    
    // Accounts
    'accounts.title': 'Gerenciar Contas',
    'accounts.add': 'Adicionar Conta',
    'accounts.name': 'Nome da Conta',
    'accounts.type': 'Tipo da Conta',
    'accounts.types.checking': 'Conta Corrente',
    'accounts.types.savings': 'Poupança',
    'accounts.types.investment': 'Investimento',
    'accounts.types.other': 'Outra',
    'accounts.models.personal': 'Pessoal',
    'accounts.models.business': 'Empresarial',
    'accounts.yourAccounts': 'Suas Contas',
    'accounts.noAccounts': 'Nenhuma conta cadastrada',
    'accounts.balance': 'Saldo',
    'accounts.bank': 'Banco',
    'accounts.selectType': 'Selecione o tipo',
    'accounts.adding': 'Adicionando...',
    'accounts.addAccount': 'Adicionar Conta',
    
    // Categories
    'categories.title': 'Gerenciar Categorias',
    'categories.add': 'Adicionar Categoria',
    'categories.name': 'Nome da Categoria',
    'categories.adding': 'Adicionando...',
    'categories.addCategory': 'Adicionar Categoria',
    'categories.all': 'Todas as Categorias',
    'categories.income': 'Categorias de Entrada',
    'categories.expense': 'Categorias de Saída',
    'categories.incomeType': 'Entrada',
    'categories.expenseType': 'Saída',
    
    // Transactions
    'transactions.recent': 'Transações Recentes',
    'transactions.noTransactions': 'Nenhuma transação registrada ainda.',
    'transactions.addFirst': 'Adicione sua primeira transação acima!',
    
    // Messages
    'messages.cardAdded': 'Cartão adicionado com sucesso!',
    'messages.cardError': 'Erro ao adicionar cartão',
    'messages.accountAdded': 'Conta adicionada com sucesso!',
    'messages.accountError': 'Erro ao carregar conta',
    'messages.accountDeleted': 'Conta removida com sucesso!',
    'messages.accountDeleteError': 'Erro ao remover conta',
    'messages.categoryAdded': 'Categoria adicionada com sucesso!',
    'messages.categoryError': 'Erro ao adicionar categoria',
    'messages.transactionAdded': 'Transação adicionada com sucesso!',
    'messages.transactionError': 'Erro ao adicionar transação',
    
    // Common
    'common.required': 'obrigatório',
    'common.error': 'Erro',
    'common.fillRequiredFields': 'Preencha todos os campos obrigatórios',
    'common.errorCreating': 'Erro ao criar investimento',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.loading': 'Carregando...',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.select': 'Selecionar',
    'back': 'Voltar',
    'accounts.manage': 'Gerenciar Contas',
    
    // Chart
    'chart.userComparison': 'Comparativo entre Usuários',
    'chart.expenses': 'Gastos',
    'chart.income': 'Receitas',
    'chart.currentMonth': 'Mês Atual',
    'chart.last3Months': '3 Meses',
    'chart.last6Months': '6 Meses',
    'chart.pieChart': 'Pizza',
    'chart.barChart': 'Barras',
    'chart.total': 'Total',
    'chart.user1': 'Usuário 1',
    'chart.user2': 'Usuário 2',
    'chart.noData': 'Nenhum {type} encontrado no período',
    'chart.expense': 'gasto',
    'chart.receipt': 'receita',
    
    // User Profile
    'userProfile.title': 'Perfil do Usuário',
    'userProfile.profile': 'Perfil',
    'userProfile.users': 'Usuários',
    'userProfile.billing': 'Faturamento',
    'userProfile.security': 'Segurança',
    'userProfile.personalInfo': 'Informações Pessoais',
    'userProfile.email': 'E-mail',
    'userProfile.displayName': 'Nome de Exibição',
    'userProfile.preferredCurrency': 'Moeda Preferida',
    'userProfile.saving': 'Salvando...',
    'userProfile.saveProfile': 'Salvar Perfil',
    'userProfile.userConfig': 'Configuração de Usuários',
    'userProfile.mainUser': 'Usuário Principal',
    'userProfile.secondUser': 'Segundo Usuário',
    'userProfile.inviteEmail': 'E-mail para Convite',
    'userProfile.sending': 'Enviando...',
    'userProfile.sendInvite': 'Enviar Convite',
    'userProfile.saveSettings': 'Salvar Configurações',
    'userProfile.billingInfo': 'Informações de Faturamento',
    'userProfile.freePlan': 'Você está no plano gratuito',
    'userProfile.upgradeText': 'Faça upgrade para acessar recursos premium',
    'userProfile.upgradePlan': 'Fazer Upgrade',
    'userProfile.changePassword': 'Alterar Senha',
    'userProfile.newPassword': 'Nova Senha',
    'userProfile.confirmPassword': 'Confirmar Senha',
    'userProfile.updating': 'Atualizando...',
    'userProfile.updatePassword': 'Atualizar Senha',
    
    // Investments
    'investments.title': 'Investimentos',
    'investments.dashboard': 'Dashboard de Investimentos',
    'investments.newInvestment': 'Novo Investimento',
    'investments.totalInvested': 'Total Investido',
    'investments.currentValue': 'Valor Atual',
    'investments.totalReturn': 'Retorno Total',
    'investments.returnPercentage': 'Retorno %',
    'investments.distribution': 'Distribuição por Tipo',
    'investments.name': 'Nome do Investimento',
    'investments.type': 'Tipo',
    'investments.amount': 'Valor Investido',
    'investments.currentValueField': 'Valor Atual',
    'investments.purchaseDate': 'Data de Compra',
    'investments.broker': 'Corretora',
    'investments.goal': 'Meta',
    'investments.currency': 'Moeda',
    'investments.notes': 'Observações',
    'investments.isShared': 'Investimento Compartilhado',
    'investments.selectType': 'Selecione o tipo',
    'investments.selectGoal': 'Selecione uma meta',
    'investments.creating': 'Criando...',
    'investments.createInvestment': 'Criar Investimento',
    'investments.goals': 'Objetivos',
    'investments.overview': 'Visão Geral',
    'investments.activeGoals': 'Objetivos Ativos',
    'investments.goalName': 'Nome da Meta',
    'investments.targetAmount': 'Valor Meta',
    'investments.currentAmount': 'Valor Atual',
    'investments.targetDate': 'Data Meta',
    'investments.description': 'Descrição',
    'investments.completed': 'Concluída',
    'investments.inProgress': 'Em Progresso',
    'investments.progress': 'Progresso',
    'investments.profitabilitySimulator': 'Simulador de Rentabilidade',
    'investments.monthlyContribution': 'Aporte Mensal',
    'investments.annualReturn': 'Retorno Anual (%)',
    'investments.timePeriod': 'Período (meses)',
    'investments.finalValue': 'Valor Final',
    'investments.totalContributions': 'Total de Aportes',
    'investments.totalInterest': 'Total de Juros',
    'investments.simulate': 'Simular',
    'investments.portfolioChart': 'Gráfico do Portfólio',
    'investments.noInvestments': 'Nenhum investimento encontrado',
    'investments.noGoals': 'Nenhuma meta encontrada',
    'investments.noData': 'Nenhum dado disponível',
    'investments.actions': 'Ações',
    'investments.date': 'Data',
    'investments.shared': 'Compartilhado',
    'investments.deleteInvestment': 'Excluir Investimento',
    'investments.deleteConfirm': 'Tem certeza que deseja excluir o investimento "{name}"? Esta ação não pode ser desfeita.',
    'investments.deleteSuccess': 'Investimento excluído com sucesso!',
    'investments.deleteError': 'Erro ao excluir investimento',
    'investments.listTitle': 'Lista de Investimentos',
    'investments.newInvestmentForm': {
      'title': 'Novo Investimento',
      'name': 'Nome do Investimento',
      'type': 'Tipo',
      'selectType': 'Selecione o tipo',
      'investedAmount': 'Valor Investido',
      'currentValue': 'Valor Atual',
      'purchaseDate': 'Data da Compra',
      'currency': 'Moeda',
      'broker': 'Corretora',
      'goal': 'Objetivo (Opcional)',
      'associateGoal': 'Associar a um objetivo',
      'noGoal': 'Nenhum objetivo',
      'sharedInvestment': 'Investimento compartilhado',
      'owner': 'Proprietário',
      'user1': 'Usuário 1',
      'user2': 'Usuário 2',
      'notes': 'Observações',
      'notesPlaceholder': 'Observações sobre o investimento...',
      'brokerPlaceholder': 'Ex: XP Investimentos',
      'namePlaceholder': 'Ex: Tesouro Selic 2027',
      'cancel': 'Cancelar',
      'save': 'Salvar Investimento',
      'saving': 'Salvando...',
      'types': {
        'renda_fixa': 'Renda Fixa',
        'renda_variavel': 'Renda Variável',
        'cripto': 'Criptomoedas',
        'fundos': 'Fundos',
        'tesouro_direto': 'Tesouro Direto'
      }
    },
    
    // Mileage
    'mileage.title': 'Sistema de Milhagem',
    'mileage.subtitle': 'Gerencie suas milhas de cartão de crédito e metas de viagem',
    'mileage.totalMiles': 'Total de Milhas',
    'mileage.milesAccumulated': 'milhas acumuladas',
    'mileage.activeCards': 'Cartões Ativos',
    'mileage.rulesConfigured': 'regras configuradas',
    'mileage.activeGoals': 'Metas Ativas',
    'mileage.inProgress': 'em progresso',
    'mileage.rules': 'Regras de Milhagem',
    'mileage.goals': 'Metas',
    'mileage.history': 'Histórico',
    'mileage.newRule': 'Nova Regra',
    'mileage.newGoal': 'Nova Meta',
    'mileage.ruleTitle': 'Nova Regra de Milhagem',
    'mileage.ruleDescription': 'Configure como as milhas são calculadas para um cartão específico',
    'mileage.card': 'Cartão',
    'mileage.selectCard': 'Selecione um cartão',
    'mileage.bankName': 'Nome do Banco',
    'mileage.bankPlaceholder': 'Ex: Nubank, Itaú, Bradesco',
    'mileage.cardBrand': 'Bandeira',
    'mileage.brandPlaceholder': 'Ex: Visa, Mastercard, Elo',
    'mileage.currency': 'Moeda',
    'mileage.milesPerAmount': 'Milhas por Valor',
    'mileage.milesPlaceholder': 'Ex: 1 (1 milha)',
    'mileage.amountThreshold': 'A cada',
    'mileage.thresholdPlaceholder': 'Ex: 3 (R$ 3,00 gastos)',
    'mileage.createRule': 'Criar Regra',
    'mileage.active': 'Ativo',
    'mileage.inactive': 'Inativo',
    'mileage.activate': 'Ativar',
    'mileage.deactivate': 'Desativar',
    'mileage.goalTitle': 'Nova Meta de Milhagem',
    'mileage.goalDescription': 'Defina uma meta para acumular milhas',
    'mileage.goalName': 'Nome da Meta',
    'mileage.goalNamePlaceholder': 'Ex: Viagem para Europa',
    'mileage.targetMiles': 'Milhas Necessárias',
    'mileage.targetMilesPlaceholder': 'Ex: 50000',
    'mileage.targetDate': 'Data Meta (Opcional)',
    'mileage.description': 'Descrição (Opcional)',
    'mileage.descriptionPlaceholder': 'Descreva sua meta...',
    'mileage.createGoal': 'Criar Meta',
    'mileage.completed': 'Concluída',
    'mileage.progressText': 'concluído',
    'mileage.target': 'Meta',
    'mileage.historyTitle': 'Histórico de Milhagem',
    'mileage.milesEarned': 'milhas',
    'mileage.spent': 'Gasto',
    'mileage.ruleCreated': 'Regra de milhagem criada com sucesso',
    'mileage.ruleCreateError': 'Erro ao criar regra de milhagem',
    'mileage.goalCreated': 'Meta de milhagem criada com sucesso',
    'mileage.goalCreateError': 'Erro ao criar meta de milhagem',
    'mileage.ruleDeleted': 'Regra deletada com sucesso',
    'mileage.ruleDeleteError': 'Erro ao deletar regra',
    'mileage.goalDeleted': 'Meta deletada com sucesso',
    'mileage.goalDeleteError': 'Erro ao deletar meta',
    'mileage.ruleStatusError': 'Erro ao atualizar status da regra',
    'mileage.backToDashboard': 'Voltar ao Dashboard',
    
    // Profitability Simulator
    'simulator.title': 'Simulador de Rentabilidade',
    'simulator.parameters': 'Parâmetros da Simulação',
    'simulator.initialAmount': 'Valor Inicial',
    'simulator.monthlyAmount': 'Aporte Mensal',
    'simulator.investmentType': 'Tipo de Investimento',
    'simulator.customRate': 'Taxa Anual (%)',
    'simulator.period': 'Período (anos)',
    'simulator.simulate': 'Simular',
    'simulator.clear': 'Limpar',
    'simulator.results': 'Resultados da Simulação',
    'simulator.finalAmount': 'Valor Final',
    'simulator.profitability': 'Rentabilidade',
    'simulator.totalInvested': 'Total Investido',
    'simulator.totalProfit': 'Lucro Total',
    'simulator.comparison': 'Comparação com outros investimentos:',
    'simulator.tips': '💡 Dicas:',
    'simulator.excellent': '• Excelente! Sua estratégia pode multiplicar o investimento.',
    'simulator.regularContributions': '• Aportes regulares potencializam os juros compostos.',
    'simulator.diversify': '• Considere diversificar entre diferentes tipos de investimento.',
    'simulator.inflation': '• Lembre-se de considerar a inflação no seu planejamento.',
    'simulator.fillData': 'Preencha os dados e clique em "Simular" para ver os resultados.',
    
    // Goals Manager
    'goals.title': 'Objetivos de Investimento',
    'goals.newGoal': 'Novo Objetivo',
    'goals.editGoal': 'Editar Objetivo',
    'goals.createGoal': 'Crie um novo objetivo de investimento',
    'goals.editGoalDesc': 'Edite as informações do objetivo',
    'goals.goalName': 'Nome do Objetivo *',
    'goals.goalNamePlaceholder': 'Ex: Comprar apartamento',
    'goals.description': 'Descrição',
    'goals.descriptionPlaceholder': 'Descrição do objetivo...',
    'goals.targetAmount': 'Valor Alvo *',
    'goals.currency': 'Moeda',
    'goals.targetDate': 'Data Alvo',
    'goals.cancel': 'Cancelar',
    'goals.saving': 'Salvando...',
    'goals.update': 'Atualizar',
    'goals.create': 'Criar',
    'goals.noGoals': 'Nenhum objetivo definido ainda. Crie seu primeiro objetivo!',
    'goals.progress': 'Progresso',
    'goals.current': 'Atual',
    'goals.target': 'Meta',
    'goals.remaining': 'Faltam',
    'goals.daysLate': 'dias atrasado',
    'goals.daysRemaining': 'dias restantes',
    'goals.deleteGoal': 'Excluir Objetivo',
    'goals.deleteConfirm': 'Tem certeza que deseja excluir o objetivo "{name}"? Esta ação não pode ser desfeita.',
    'goals.delete': 'Excluir',
    'goals.fillRequired': 'Preencha todos os campos obrigatórios',
    'goals.updateSuccess': 'Objetivo atualizado com sucesso!',
    'goals.createSuccess': 'Objetivo criado com sucesso!',
    'goals.deleteSuccess': 'Objetivo excluído com sucesso!',
    'goals.saveError': 'Erro ao salvar objetivo',
    'goals.deleteError': 'Erro ao excluir objetivo',
  },
  en: {
    // Dashboard
    'dashboard.title': 'Financial Management for Couples',
    'dashboard.subtitle': 'Control your finances intelligently',
    'dashboard.balance': 'Total Balance',
    'dashboard.income': 'Income',
    'dashboard.expenses': 'Expenses',
    'dashboard.addTransaction': 'Add Transaction',
    'dashboard.viewMode': 'View Mode',
    'dashboard.both': 'Both',
    'dashboard.user1': 'User 1',
    'dashboard.user2': 'User 2',
    'dashboard.vsPreviousMonth': 'vs previous month',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Monthly Expenses',
    'nav.categories': 'Categories',
    'nav.recurring': 'Recurring Expenses',
    'nav.cards': 'Cards',
    'nav.accounts': 'Accounts',
    'nav.profile': 'Profile',
    'nav.investments': 'Investments',
    'nav.mileage': 'Mileage',
    'nav.back': 'Back',
    
    // Transactions
    'transaction.add': 'Add Transaction',
    'transaction.type': 'Type',
    'transaction.income': 'Income',
    'transaction.expense': 'Expense',
    'transaction.amount': 'Amount',
    'transaction.description': 'Description',
    'transaction.category': 'Category',
    'transaction.date': 'Date',
    'transaction.paymentMethod': 'Payment Method',
    'transaction.cash': 'Cash',
    'transaction.creditCard': 'Credit Card',
    'transaction.debitCard': 'Debit Card',
    'transaction.bankTransfer': 'Bank Transfer',
    'transaction.pix': 'PIX',
    'transaction.submit': 'Add',
    'transaction.submitting': 'Adding...',
    
    // TransactionForm specific translations
    'transactionForm.title': 'New Transaction',
    'transactionForm.income': 'Income',
    'transactionForm.expense': 'Expense',
    'transactionForm.transactionDate': 'Transaction Date',
    'transactionForm.selectDate': 'Select date',
    'transactionForm.amount': 'Amount',
    'transactionForm.description': 'Description',
    'transactionForm.receiptMethod': 'Receipt Method',
    'transactionForm.paymentMethod': 'Payment Method',
    'transactionForm.selectPaymentMethod': 'Select method',
    'transactionForm.cash': 'Cash',
    'transactionForm.deposit': 'Deposit',
    'transactionForm.transfer': 'Transfer',
    'transactionForm.debitCard': 'Debit Card',
    'transactionForm.creditCard': 'Credit Card',
    'transactionForm.card': 'Card',
    'transactionForm.selectCard': 'Select card',
    'transactionForm.selectCardPlaceholder': 'Select card',
    'transactionForm.account': 'Bank Account',
    'transactionForm.selectAccount': 'Select account',
    'transactionForm.selectAccountPlaceholder': 'Select account',
    'transactionForm.installmentPayment': 'Installment payment',
    'transactionForm.installments': 'Installments',
    'transactionForm.selectInstallments': 'Select installments',
    'transactionForm.category': 'Category',
    'transactionForm.selectCategory': 'Select category',
    'transactionForm.subcategory': 'Subcategory',
    'transactionForm.currency': 'Currency',
    'transactionForm.addTransaction': 'Add Transaction',
    
    // Cards
    'cards.title': 'Manage Cards',
    'cards.manage': 'Manage Cards',
    'cards.add': 'Add Card',
    'cards.name': 'Card Name',
    'cards.type': 'Card Type',
    'cards.credit': 'Credit',
    'cards.debit': 'Debit',
    'cards.lastFourDigits': 'Last 4 Digits',
    'cards.creditLimit': 'Credit Limit',
    'cards.currentBalance': 'Current Balance',
    'cards.currency': 'Currency',
    'cards.dueDate': 'Due Date',
    'cards.selectType': 'Select type',
    'cards.selectDay': 'Select day',
    'cards.adding': 'Adding...',
    'cards.addCard': 'Add Card',
    
    // Accounts
    'accounts.title': 'Manage Accounts',
    'accounts.add': 'Add Account',
    'accounts.name': 'Account Name',
    'accounts.type': 'Account Type',
    'accounts.types.checking': 'Checking',
    'accounts.types.savings': 'Savings',
    'accounts.types.investment': 'Investment',
    'accounts.types.other': 'Other',
    'accounts.models.personal': 'Personal',
    'accounts.models.business': 'Business',
    'accounts.yourAccounts': 'Your Accounts',
    'accounts.noAccounts': 'No accounts registered',
    'accounts.balance': 'Balance',
    'accounts.bank': 'Bank',
    'accounts.selectType': 'Select type',
    'accounts.adding': 'Adding...',
    'accounts.addAccount': 'Add Account',
    
    // Categories
    'categories.title': 'Manage Categories',
    'categories.add': 'Add Category',
    'categories.name': 'Category Name',
    'categories.adding': 'Adding...',
    'categories.addCategory': 'Add Category',
    'categories.all': 'All Categories',
    'categories.income': 'Income Categories',
    'categories.expense': 'Expense Categories',
    'categories.incomeType': 'Income',
    'categories.expenseType': 'Expense',
    
    // Transactions
    'transactions.recent': 'Recent Transactions',
    'transactions.noTransactions': 'No transactions recorded yet.',
    'transactions.addFirst': 'Add your first transaction above!',
    
    // Messages
    'messages.cardAdded': 'Card added successfully!',
    'messages.cardError': 'Error adding card',
    'messages.accountAdded': 'Account added successfully!',
    'messages.accountError': 'Error loading account',
    'messages.accountDeleted': 'Account removed successfully!',
    'messages.accountDeleteError': 'Error removing account',
    'messages.categoryAdded': 'Category added successfully!',
    'messages.categoryError': 'Error adding category',
    'messages.transactionAdded': 'Transaction added successfully!',
    'messages.transactionError': 'Error adding transaction',
    
    // Common
    'common.required': 'required',
    'common.error': 'Error',
    'common.fillRequiredFields': 'Fill in all required fields',
    'common.errorCreating': 'Error creating investment',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'back': 'Back',
    'accounts.manage': 'Manage Accounts',
    
    // Chart
    'chart.userComparison': 'User Comparison',
    'chart.expenses': 'Expenses',
    'chart.income': 'Income',
    'chart.currentMonth': 'Current Month',
    'chart.last3Months': '3 Months',
    'chart.last6Months': '6 Months',
    'chart.pieChart': 'Pie',
    'chart.barChart': 'Bar',
    'chart.total': 'Total',
    'chart.user1': 'User 1',
    'chart.user2': 'User 2',
    'chart.noData': 'No {type} found in the period',
    'chart.expense': 'expense',
    'chart.receipt': 'income',
    
    // User Profile
    'userProfile.title': 'User Profile',
    'userProfile.profile': 'Profile',
    'userProfile.users': 'Users',
    'userProfile.billing': 'Billing',
    'userProfile.security': 'Security',
    'userProfile.personalInfo': 'Personal Information',
    'userProfile.email': 'Email',
    'userProfile.displayName': 'Display Name',
    'userProfile.preferredCurrency': 'Preferred Currency',
    'userProfile.saving': 'Saving...',
    'userProfile.saveProfile': 'Save Profile',
    'userProfile.userConfig': 'User Configuration',
    'userProfile.mainUser': 'Main User',
    'userProfile.secondUser': 'Second User',
    'userProfile.inviteEmail': 'Invite Email',
    'userProfile.sending': 'Sending...',
    'userProfile.sendInvite': 'Send Invite',
    'userProfile.saveSettings': 'Save Settings',
    'userProfile.billingInfo': 'Billing Information',
    'userProfile.freePlan': 'You are on the free plan',
    'userProfile.upgradeText': 'Upgrade to access premium features',
    'userProfile.upgradePlan': 'Upgrade Plan',
    'userProfile.changePassword': 'Change Password',
    'userProfile.newPassword': 'New Password',
    'userProfile.confirmPassword': 'Confirm Password',
    'userProfile.updating': 'Updating...',
    'userProfile.updatePassword': 'Update Password',
    
    // Investments
    'investments.title': 'Investments',
    'investments.dashboard': 'Investment Dashboard',
    'investments.newInvestment': 'New Investment',
    'investments.totalInvested': 'Total Invested',
    'investments.currentValue': 'Current Value',
    'investments.totalReturn': 'Total Return',
    'investments.returnPercentage': 'Return %',
    'investments.distribution': 'Distribution by Type',
    'investments.name': 'Investment Name',
    'investments.type': 'Type',
    'investments.amount': 'Invested Amount',
    'investments.currentValueField': 'Current Value',
    'investments.purchaseDate': 'Purchase Date',
    'investments.broker': 'Broker',
    'investments.goal': 'Goal',
    'investments.currency': 'Currency',
    'investments.notes': 'Notes',
    'investments.isShared': 'Shared Investment',
    'investments.selectType': 'Select type',
    'investments.selectGoal': 'Select a goal',
    'investments.creating': 'Creating...',
    'investments.createInvestment': 'Create Investment',
    'investments.goals': 'Goals',
    'investments.overview': 'Overview',
    'investments.activeGoals': 'Active Goals',
    'investments.goalName': 'Goal Name',
    'investments.targetAmount': 'Target Amount',
    'investments.currentAmount': 'Current Amount',
    'investments.targetDate': 'Target Date',
    'investments.description': 'Description',
    'investments.completed': 'Completed',
    'investments.inProgress': 'In Progress',
    'investments.progress': 'Progress',
    'investments.profitabilitySimulator': 'Profitability Simulator',
    'investments.monthlyContribution': 'Monthly Contribution',
    'investments.annualReturn': 'Annual Return (%)',
    'investments.timePeriod': 'Time Period (months)',
    'investments.finalValue': 'Final Value',
    'investments.totalContributions': 'Total Contributions',
    'investments.totalInterest': 'Total Interest',
    'investments.simulate': 'Simulate',
    'investments.portfolioChart': 'Portfolio Chart',
    'investments.noInvestments': 'No investments found',
    'investments.noGoals': 'No goals found',
    'investments.noData': 'No data available',
    'investments.actions': 'Actions',
    'investments.date': 'Date',
    'investments.shared': 'Shared',
    'investments.deleteInvestment': 'Delete Investment',
    'investments.deleteConfirm': 'Are you sure you want to delete the investment "{name}"? This action cannot be undone.',
    'investments.deleteSuccess': 'Investment deleted successfully!',
    'investments.deleteError': 'Error deleting investment',
    'investments.listTitle': 'Investment List',
    'investments.newInvestmentForm': {
      'title': 'New Investment',
      'name': 'Investment Name',
      'type': 'Type',
      'selectType': 'Select type',
      'investedAmount': 'Invested Amount',
      'currentValue': 'Current Value',
      'purchaseDate': 'Purchase Date',
      'currency': 'Currency',
      'broker': 'Broker',
      'goal': 'Goal (Optional)',
      'associateGoal': 'Associate with a goal',
      'noGoal': 'No goal',
      'sharedInvestment': 'Shared investment',
      'owner': 'Owner',
      'user1': 'User 1',
      'user2': 'User 2',
      'notes': 'Notes',
      'notesPlaceholder': 'Notes about the investment...',
      'brokerPlaceholder': 'Ex: XP Investimentos',
      'namePlaceholder': 'Ex: Treasury Bond 2027',
      'cancel': 'Cancel',
      'save': 'Save Investment',
      'saving': 'Saving...',
      'types': {
        'renda_fixa': 'Fixed Income',
        'renda_variavel': 'Variable Income',
        'cripto': 'Cryptocurrencies',
        'fundos': 'Funds',
        'tesouro_direto': 'Treasury Direct'
      }
    },
    
    // Mileage
    'mileage.title': 'Mileage System',
    'mileage.subtitle': 'Manage your credit card miles and travel goals',
    'mileage.totalMiles': 'Total Miles',
    'mileage.milesAccumulated': 'miles accumulated',
    'mileage.activeCards': 'Active Cards',
    'mileage.rulesConfigured': 'rules configured',
    'mileage.activeGoals': 'Active Goals',
    'mileage.inProgress': 'in progress',
    'mileage.rules': 'Mileage Rules',
    'mileage.goals': 'Goals',
    'mileage.history': 'History',
    'mileage.newRule': 'New Rule',
    'mileage.newGoal': 'New Goal',
    'mileage.ruleTitle': 'New Mileage Rule',
    'mileage.ruleDescription': 'Configure how miles are calculated for a specific card',
    'mileage.card': 'Card',
    'mileage.selectCard': 'Select a card',
    'mileage.bankName': 'Bank Name',
    'mileage.bankPlaceholder': 'Ex: Nubank, Itaú, Bradesco',
    'mileage.cardBrand': 'Card Brand',
    'mileage.brandPlaceholder': 'Ex: Visa, Mastercard, Elo',
    'mileage.currency': 'Currency',
    'mileage.milesPerAmount': 'Miles per Amount',
    'mileage.milesPlaceholder': 'Ex: 1 (1 mile)',
    'mileage.amountThreshold': 'Every',
    'mileage.thresholdPlaceholder': 'Ex: 3 ($3.00 spent)',
    'mileage.createRule': 'Create Rule',
    'mileage.active': 'Active',
    'mileage.inactive': 'Inactive',
    'mileage.activate': 'Activate',
    'mileage.deactivate': 'Deactivate',
    'mileage.goalTitle': 'New Mileage Goal',
    'mileage.goalDescription': 'Set a goal to accumulate miles',
    'mileage.goalName': 'Goal Name',
    'mileage.goalNamePlaceholder': 'Ex: Trip to Europe',
    'mileage.targetMiles': 'Required Miles',
    'mileage.targetMilesPlaceholder': 'Ex: 50000',
    'mileage.targetDate': 'Target Date (Optional)',
    'mileage.description': 'Description (Optional)',
    'mileage.descriptionPlaceholder': 'Describe your goal...',
    'mileage.createGoal': 'Create Goal',
    'mileage.completed': 'Completed',
    'mileage.progressText': 'completed',
    'mileage.target': 'Target',
    'mileage.historyTitle': 'Mileage History',
    'mileage.milesEarned': 'miles',
    'mileage.spent': 'Spent',
    'mileage.ruleCreated': 'Mileage rule created successfully',
    'mileage.ruleCreateError': 'Error creating mileage rule',
    'mileage.goalCreated': 'Mileage goal created successfully',
    'mileage.goalCreateError': 'Error creating mileage goal',
    'mileage.ruleDeleted': 'Rule deleted successfully',
    'mileage.ruleDeleteError': 'Error deleting rule',
    'mileage.goalDeleted': 'Goal deleted successfully',
    'mileage.goalDeleteError': 'Error deleting goal',
    'mileage.ruleStatusError': 'Error updating rule status',
    'mileage.backToDashboard': 'Back to Dashboard',
    
    // Profitability Simulator
    'simulator.title': 'Profitability Simulator',
    'simulator.parameters': 'Simulation Parameters',
    'simulator.initialAmount': 'Initial Amount',
    'simulator.monthlyAmount': 'Monthly Contribution',
    'simulator.investmentType': 'Investment Type',
    'simulator.customRate': 'Annual Rate (%)',
    'simulator.period': 'Period (years)',
    'simulator.simulate': 'Simulate',
    'simulator.clear': 'Clear',
    'simulator.results': 'Simulation Results',
    'simulator.finalAmount': 'Final Amount',
    'simulator.profitability': 'Profitability',
    'simulator.totalInvested': 'Total Invested',
    'simulator.totalProfit': 'Total Profit',
    'simulator.comparison': 'Comparison with other investments:',
    'simulator.tips': '💡 Tips:',
    'simulator.excellent': '• Excellent! Your strategy can multiply the investment.',
    'simulator.regularContributions': '• Regular contributions enhance compound interest.',
    'simulator.diversify': '• Consider diversifying among different types of investments.',
    'simulator.inflation': '• Remember to consider inflation in your planning.',
    'simulator.fillData': 'Fill in the data and click "Simulate" to see the results.',
    
    // Goals Manager
    'goals.title': 'Investment Goals',
    'goals.newGoal': 'New Goal',
    'goals.editGoal': 'Edit Goal',
    'goals.createGoal': 'Create a new investment goal',
    'goals.editGoalDesc': 'Edit the goal information',
    'goals.goalName': 'Goal Name *',
    'goals.goalNamePlaceholder': 'Ex: Buy apartment',
    'goals.description': 'Description',
    'goals.descriptionPlaceholder': 'Goal description...',
    'goals.targetAmount': 'Target Amount *',
    'goals.currency': 'Currency',
    'goals.targetDate': 'Target Date',
    'goals.cancel': 'Cancel',
    'goals.saving': 'Saving...',
    'goals.update': 'Update',
    'goals.create': 'Create',
    'goals.noGoals': 'No goals defined yet. Create your first goal!',
    'goals.progress': 'Progress',
    'goals.current': 'Current',
    'goals.target': 'Target',
    'goals.remaining': 'Remaining',
    'goals.daysLate': 'days late',
    'goals.daysRemaining': 'days remaining',
    'goals.deleteGoal': 'Delete Goal',
    'goals.deleteConfirm': 'Are you sure you want to delete the goal "{name}"? This action cannot be undone.',
    'goals.delete': 'Delete',
    'goals.fillRequired': 'Fill in all required fields',
    'goals.updateSuccess': 'Goal updated successfully!',
    'goals.createSuccess': 'Goal created successfully!',
    'goals.deleteSuccess': 'Goal deleted successfully!',
    'goals.saveError': 'Error saving goal',
    'goals.deleteError': 'Error deleting goal',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'pt' | 'en'>('pt');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};