import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'pt' | 'en';
  setLanguage: (lang: 'pt' | 'en') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Dashboard
    'dashboard.title': 'Gestão Financeira para Casais',
    'dashboard.subtitle': 'Controle suas finanças de forma inteligente',
    'dashboard.balance': 'Saldo Total',
    'dashboard.income': 'Receitas',
    'dashboard.expenses': 'Despesas',
    'dashboard.addTransaction': 'Adicionar Transação',
    'dashboard.viewMode': 'Modo de Visualização',
    'dashboard.both': 'Ambos',
    'dashboard.user1': 'Usuário 1',
    'dashboard.user2': 'Usuário 2',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Gastos Mensais',
    'nav.categories': 'Categorias',
    'nav.recurring': 'Gastos Recorrentes',
    'nav.cards': 'Cartões',
    'nav.accounts': 'Contas',
    'nav.profile': 'Perfil',
    'nav.back': 'Voltar',
    
    // Transactions
    'transaction.add': 'Adicionar Transação',
    'transaction.type': 'Tipo',
    'transaction.income': 'Receita',
    'transaction.expense': 'Despesa',
    'transaction.amount': 'Valor',
    'transaction.description': 'Descrição',
    'transaction.category': 'Categoria',
    'transaction.date': 'Data',
    'transaction.paymentMethod': 'Método de Pagamento',
    'transaction.cash': 'Dinheiro',
    'transaction.creditCard': 'Cartão de Crédito',
    'transaction.debitCard': 'Cartão de Débito',
    'transaction.bankTransfer': 'Transferência Bancária',
    'transaction.pix': 'PIX',
    'transaction.submit': 'Adicionar',
    'transaction.submitting': 'Adicionando...',
    
    // TransactionForm specific translations
    'transactionForm.title': 'Nova Transação',
    'transactionForm.income': 'Receita',
    'transactionForm.expense': 'Despesa',
    'transactionForm.transactionDate': 'Data da Transação',
    'transactionForm.selectDate': 'Selecionar data',
    'transactionForm.amount': 'Valor',
    'transactionForm.description': 'Descrição',
    'transactionForm.receiptMethod': 'Método de Recebimento',
    'transactionForm.paymentMethod': 'Método de Pagamento',
    'transactionForm.selectPaymentMethod': 'Selecionar método',
    'transactionForm.cash': 'Dinheiro',
    'transactionForm.deposit': 'Depósito',
    'transactionForm.transfer': 'Transferência',
    'transactionForm.card': 'Cartão',
    'transactionForm.selectCard': 'Selecionar cartão',
    'transactionForm.account': 'Conta Bancária',
    'transactionForm.selectAccount': 'Selecione a conta',
    'transactionForm.installmentPayment': 'Pagamento parcelado',
    'transactionForm.installments': 'Parcelas',
    'transactionForm.selectInstallments': 'Selecionar parcelas',
    'transactionForm.category': 'Categoria',
    'transactionForm.selectCategory': 'Selecionar categoria',
    'transactionForm.subcategory': 'Subcategoria',
    'transactionForm.currency': 'Moeda',
    'transactionForm.addTransaction': 'Adicionar Transação',
    
    // Cards
    'cards.title': 'Gerenciar Cartões',
    'cards.manage': 'Gerenciar Cartões',
    'cards.add': 'Adicionar Cartão',
    'cards.name': 'Nome do Cartão',
    'cards.type': 'Tipo do Cartão',
    'cards.credit': 'Crédito',
    'cards.debit': 'Débito',
    'cards.lastFourDigits': 'Últimos 4 Dígitos',
    'cards.creditLimit': 'Limite de Crédito',
    'cards.currentBalance': 'Saldo Atual',
    'cards.currency': 'Moeda',
    'cards.dueDate': 'Data de Vencimento',
    'cards.selectType': 'Selecione o tipo',
    'cards.selectDay': 'Selecione o dia',
    'cards.adding': 'Adicionando...',
    'cards.addCard': 'Adicionar Cartão',
    
    // Accounts
    'accounts.title': 'Gerenciar Contas',
    'accounts.add': 'Adicionar Conta',
    'accounts.name': 'Nome da Conta',
    'accounts.type': 'Tipo da Conta',
    'accounts.types.checking': 'Conta Corrente',
    'accounts.types.savings': 'Poupança',
    'accounts.types.investment': 'Investimento',
    'accounts.types.other': 'Outra',
    'accounts.models.personal': 'Pessoal',
    'accounts.models.business': 'Empresarial',
    'accounts.yourAccounts': 'Suas Contas',
    'accounts.noAccounts': 'Nenhuma conta cadastrada',
    'accounts.balance': 'Saldo',
    'accounts.bank': 'Banco',
    'accounts.selectType': 'Selecione o tipo',
    'accounts.adding': 'Adicionando...',
    'accounts.addAccount': 'Adicionar Conta',
    
    // Categories
    'categories.title': 'Gerenciar Categorias',
    'categories.add': 'Adicionar Categoria',
    'categories.name': 'Nome da Categoria',
    'categories.adding': 'Adicionando...',
    'categories.addCategory': 'Adicionar Categoria',
    
    // Messages
    'messages.cardAdded': 'Cartão adicionado com sucesso!',
    'messages.cardError': 'Erro ao adicionar cartão',
    'messages.accountAdded': 'Conta adicionada com sucesso!',
    'messages.accountError': 'Erro ao carregar conta',
    'messages.accountDeleted': 'Conta removida com sucesso!',
    'messages.accountDeleteError': 'Erro ao remover conta',
    'messages.categoryAdded': 'Categoria adicionada com sucesso!',
    'messages.categoryError': 'Erro ao adicionar categoria',
    'messages.transactionAdded': 'Transação adicionada com sucesso!',
    'messages.transactionError': 'Erro ao adicionar transação',
    
    // Common
    'common.required': 'obrigatório',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.loading': 'Carregando...',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.select': 'Selecionar',
    'back': 'Voltar',
    'accounts.manage': 'Gerenciar Contas',
    
    // Chart
    'chart.userComparison': 'Comparativo entre Usuários',
    'chart.expenses': 'Gastos',
    'chart.income': 'Receitas',
    'chart.currentMonth': 'Mês Atual',
    'chart.last3Months': '3 Meses',
    'chart.last6Months': '6 Meses',
    'chart.pieChart': 'Pizza',
    'chart.barChart': 'Barras',
    'chart.total': 'Total',
    'chart.user1': 'Usuário 1',
    'chart.user2': 'Usuário 2',
    'chart.noData': 'Nenhum {type} encontrado no período',
    'chart.expense': 'gasto',
    'chart.receipt': 'receita',
    
    // User Profile
    'userProfile.title': 'Perfil do Usuário',
    'userProfile.profile': 'Perfil',
    'userProfile.users': 'Usuários',
    'userProfile.billing': 'Faturamento',
    'userProfile.security': 'Segurança',
    'userProfile.personalInfo': 'Informações Pessoais',
    'userProfile.email': 'E-mail',
    'userProfile.displayName': 'Nome de Exibição',
    'userProfile.preferredCurrency': 'Moeda Preferida',
    'userProfile.saving': 'Salvando...',
    'userProfile.saveProfile': 'Salvar Perfil',
    'userProfile.userConfig': 'Configuração de Usuários',
    'userProfile.mainUser': 'Usuário Principal',
    'userProfile.secondUser': 'Segundo Usuário',
    'userProfile.inviteEmail': 'E-mail para Convite',
    'userProfile.sending': 'Enviando...',
    'userProfile.sendInvite': 'Enviar Convite',
    'userProfile.saveSettings': 'Salvar Configurações',
    'userProfile.billingInfo': 'Informações de Faturamento',
    'userProfile.freePlan': 'Você está no plano gratuito',
    'userProfile.upgradeText': 'Faça upgrade para acessar recursos premium',
    'userProfile.upgradePlan': 'Fazer Upgrade',
    'userProfile.changePassword': 'Alterar Senha',
    'userProfile.newPassword': 'Nova Senha',
    'userProfile.confirmPassword': 'Confirmar Senha',
    'userProfile.updating': 'Atualizando...',
    'userProfile.updatePassword': 'Atualizar Senha',
  },
  en: {
    // Dashboard
    'dashboard.title': 'Financial Management for Couples',
    'dashboard.subtitle': 'Control your finances intelligently',
    'dashboard.balance': 'Total Balance',
    'dashboard.income': 'Income',
    'dashboard.expenses': 'Expenses',
    'dashboard.addTransaction': 'Add Transaction',
    'dashboard.viewMode': 'View Mode',
    'dashboard.both': 'Both',
    'dashboard.user1': 'User 1',
    'dashboard.user2': 'User 2',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.monthlyExpenses': 'Monthly Expenses',
    'nav.categories': 'Categories',
    'nav.recurring': 'Recurring Expenses',
    'nav.cards': 'Cards',
    'nav.accounts': 'Accounts',
    'nav.profile': 'Profile',
    'nav.back': 'Back',
    
    // Transactions
    'transaction.add': 'Add Transaction',
    'transaction.type': 'Type',
    'transaction.income': 'Income',
    'transaction.expense': 'Expense',
    'transaction.amount': 'Amount',
    'transaction.description': 'Description',
    'transaction.category': 'Category',
    'transaction.date': 'Date',
    'transaction.paymentMethod': 'Payment Method',
    'transaction.cash': 'Cash',
    'transaction.creditCard': 'Credit Card',
    'transaction.debitCard': 'Debit Card',
    'transaction.bankTransfer': 'Bank Transfer',
    'transaction.pix': 'PIX',
    'transaction.submit': 'Add',
    'transaction.submitting': 'Adding...',
    
    // TransactionForm specific translations
    'transactionForm.title': 'New Transaction',
    'transactionForm.income': 'Income',
    'transactionForm.expense': 'Expense',
    'transactionForm.transactionDate': 'Transaction Date',
    'transactionForm.selectDate': 'Select date',
    'transactionForm.amount': 'Amount',
    'transactionForm.description': 'Description',
    'transactionForm.receiptMethod': 'Receipt Method',
    'transactionForm.paymentMethod': 'Payment Method',
    'transactionForm.selectPaymentMethod': 'Select method',
    'transactionForm.cash': 'Cash',
    'transactionForm.deposit': 'Deposit',
    'transactionForm.transfer': 'Transfer',
    'transactionForm.card': 'Card',
    'transactionForm.selectCard': 'Select card',
    'transactionForm.account': 'Bank Account',
    'transactionForm.selectAccount': 'Select account',
    'transactionForm.installmentPayment': 'Installment payment',
    'transactionForm.installments': 'Installments',
    'transactionForm.selectInstallments': 'Select installments',
    'transactionForm.category': 'Category',
    'transactionForm.selectCategory': 'Select category',
    'transactionForm.subcategory': 'Subcategory',
    'transactionForm.currency': 'Currency',
    'transactionForm.addTransaction': 'Add Transaction',
    
    // Cards
    'cards.title': 'Manage Cards',
    'cards.manage': 'Manage Cards',
    'cards.add': 'Add Card',
    'cards.name': 'Card Name',
    'cards.type': 'Card Type',
    'cards.credit': 'Credit',
    'cards.debit': 'Debit',
    'cards.lastFourDigits': 'Last 4 Digits',
    'cards.creditLimit': 'Credit Limit',
    'cards.currentBalance': 'Current Balance',
    'cards.currency': 'Currency',
    'cards.dueDate': 'Due Date',
    'cards.selectType': 'Select type',
    'cards.selectDay': 'Select day',
    'cards.adding': 'Adding...',
    'cards.addCard': 'Add Card',
    
    // Accounts
    'accounts.title': 'Manage Accounts',
    'accounts.add': 'Add Account',
    'accounts.name': 'Account Name',
    'accounts.type': 'Account Type',
    'accounts.types.checking': 'Checking',
    'accounts.types.savings': 'Savings',
    'accounts.types.investment': 'Investment',
    'accounts.types.other': 'Other',
    'accounts.models.personal': 'Personal',
    'accounts.models.business': 'Business',
    'accounts.yourAccounts': 'Your Accounts',
    'accounts.noAccounts': 'No accounts registered',
    'accounts.balance': 'Balance',
    'accounts.bank': 'Bank',
    'accounts.selectType': 'Select type',
    'accounts.adding': 'Adding...',
    'accounts.addAccount': 'Add Account',
    
    // Categories
    'categories.title': 'Manage Categories',
    'categories.add': 'Add Category',
    'categories.name': 'Category Name',
    'categories.adding': 'Adding...',
    'categories.addCategory': 'Add Category',
    
    // Messages
    'messages.cardAdded': 'Card added successfully!',
    'messages.cardError': 'Error adding card',
    'messages.accountAdded': 'Account added successfully!',
    'messages.accountError': 'Error loading account',
    'messages.accountDeleted': 'Account removed successfully!',
    'messages.accountDeleteError': 'Error removing account',
    'messages.categoryAdded': 'Category added successfully!',
    'messages.categoryError': 'Error adding category',
    'messages.transactionAdded': 'Transaction added successfully!',
    'messages.transactionError': 'Error adding transaction',
    
    // Common
    'common.required': 'required',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'back': 'Back',
    'accounts.manage': 'Manage Accounts',
    
    // Chart
    'chart.userComparison': 'User Comparison',
    'chart.expenses': 'Expenses',
    'chart.income': 'Income',
    'chart.currentMonth': 'Current Month',
    'chart.last3Months': '3 Months',
    'chart.last6Months': '6 Months',
    'chart.pieChart': 'Pie',
    'chart.barChart': 'Bar',
    'chart.total': 'Total',
    'chart.user1': 'User 1',
    'chart.user2': 'User 2',
    'chart.noData': 'No {type} found in the period',
    'chart.expense': 'expense',
    'chart.receipt': 'income',
    
    // User Profile
    'userProfile.title': 'User Profile',
    'userProfile.profile': 'Profile',
    'userProfile.users': 'Users',
    'userProfile.billing': 'Billing',
    'userProfile.security': 'Security',
    'userProfile.personalInfo': 'Personal Information',
    'userProfile.email': 'Email',
    'userProfile.displayName': 'Display Name',
    'userProfile.preferredCurrency': 'Preferred Currency',
    'userProfile.saving': 'Saving...',
    'userProfile.saveProfile': 'Save Profile',
    'userProfile.userConfig': 'User Configuration',
    'userProfile.mainUser': 'Main User',
    'userProfile.secondUser': 'Second User',
    'userProfile.inviteEmail': 'Invite Email',
    'userProfile.sending': 'Sending...',
    'userProfile.sendInvite': 'Send Invite',
    'userProfile.saveSettings': 'Save Settings',
    'userProfile.billingInfo': 'Billing Information',
    'userProfile.freePlan': 'You are on the free plan',
    'userProfile.upgradeText': 'Upgrade to access premium features',
    'userProfile.upgradePlan': 'Upgrade Plan',
    'userProfile.changePassword': 'Change Password',
    'userProfile.newPassword': 'New Password',
    'userProfile.confirmPassword': 'Confirm Password',
    'userProfile.updating': 'Updating...',
    'userProfile.updatePassword': 'Update Password',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'pt' | 'en'>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['pt']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};